"""Added shipment date and economy share features

Revision ID: 1fd382fcc0b0
Revises: 
Create Date: 2016-02-28 17:23:26.876000

"""

# revision identifiers, used by Alembic.
revision = '1fd382fcc0b0'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import db_utils

from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_flows', sa.Column('economy_orders_share', db_utils.SqliteNumeric(), nullable=True))
    op.add_column('material_flows', sa.Column('last_shipment_date', sa.DateTime(), nullable=True))
    op.add_column('material_flows', sa.Column('next_expected_shipment_date', sa.DateTime(), nullable=True))
    op.drop_column('material_flows', 'put_supplier_order_if_not_available')
    op.drop_column('material_flows', 'next_expected_order_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_flows', sa.Column('next_expected_order_date', mysql.DATETIME(), nullable=True))
    op.add_column('material_flows', sa.Column('put_supplier_order_if_not_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('material_flows', 'next_expected_shipment_date')
    op.drop_column('material_flows', 'last_shipment_date')
    op.drop_column('material_flows', 'economy_orders_share')
    ### end Alembic commands ###
