# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Code\SimpleBusiness\ui\Dialog_EditMatFlow.ui'
#
# Created: Sun Feb 28 18:53:43 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_EditMatFlow(object):
    def setupUi(self, Dialog_EditMatFlow):
        Dialog_EditMatFlow.setObjectName(_fromUtf8("Dialog_EditMatFlow"))
        Dialog_EditMatFlow.resize(500, 400)
        Dialog_EditMatFlow.setMinimumSize(QtCore.QSize(400, 400))
        Dialog_EditMatFlow.setMaximumSize(QtCore.QSize(500, 600))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_EditMatFlow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog_EditMatFlow)
        self.label.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_material_type = QtGui.QComboBox(Dialog_EditMatFlow)
        self.comboBox_material_type.setObjectName(_fromUtf8("comboBox_material_type"))
        self.horizontalLayout.addWidget(self.comboBox_material_type)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_cons_volume_mean = QtGui.QLineEdit(Dialog_EditMatFlow)
        self.lineEdit_cons_volume_mean.setObjectName(_fromUtf8("lineEdit_cons_volume_mean"))
        self.gridLayout.addWidget(self.lineEdit_cons_volume_mean, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.lineEdit_cons_vol_dev = QtGui.QLineEdit(Dialog_EditMatFlow)
        self.lineEdit_cons_vol_dev.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_cons_vol_dev.setObjectName(_fromUtf8("lineEdit_cons_vol_dev"))
        self.gridLayout.addWidget(self.lineEdit_cons_vol_dev, 0, 4, 1, 1)
        self.label_MeasUnit = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_MeasUnit.setObjectName(_fromUtf8("label_MeasUnit"))
        self.gridLayout.addWidget(self.label_MeasUnit, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_cons_period_mean = QtGui.QLineEdit(Dialog_EditMatFlow)
        self.lineEdit_cons_period_mean.setObjectName(_fromUtf8("lineEdit_cons_period_mean"))
        self.gridLayout.addWidget(self.lineEdit_cons_period_mean, 1, 1, 1, 1)
        self.lineEdit_cons_period_std = QtGui.QLineEdit(Dialog_EditMatFlow)
        self.lineEdit_cons_period_std.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_cons_period_std.setObjectName(_fromUtf8("lineEdit_cons_period_std"))
        self.gridLayout.addWidget(self.lineEdit_cons_period_std, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.dateEdit_NextExpectedOrder = QtGui.QDateEdit(Dialog_EditMatFlow)
        self.dateEdit_NextExpectedOrder.setObjectName(_fromUtf8("dateEdit_NextExpectedOrder"))
        self.gridLayout.addWidget(self.dateEdit_NextExpectedOrder, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_8 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_12 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.horizontalSlider_EconomyShare = QtGui.QSlider(Dialog_EditMatFlow)
        self.horizontalSlider_EconomyShare.setMaximum(100)
        self.horizontalSlider_EconomyShare.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_EconomyShare.setObjectName(_fromUtf8("horizontalSlider_EconomyShare"))
        self.horizontalLayout_4.addWidget(self.horizontalSlider_EconomyShare)
        self.label_11 = QtGui.QLabel(Dialog_EditMatFlow)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_EstimateStatistics = QtGui.QPushButton(Dialog_EditMatFlow)
        self.pushButton_EstimateStatistics.setObjectName(_fromUtf8("pushButton_EstimateStatistics"))
        self.horizontalLayout_6.addWidget(self.pushButton_EstimateStatistics)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_down_025 = QtGui.QPushButton(Dialog_EditMatFlow)
        self.pushButton_down_025.setObjectName(_fromUtf8("pushButton_down_025"))
        self.horizontalLayout_6.addWidget(self.pushButton_down_025)
        self.pushButton_up_025 = QtGui.QPushButton(Dialog_EditMatFlow)
        self.pushButton_up_025.setObjectName(_fromUtf8("pushButton_up_025"))
        self.horizontalLayout_6.addWidget(self.pushButton_up_025)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line = QtGui.QFrame(Dialog_EditMatFlow)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_normalize_probs = QtGui.QPushButton(Dialog_EditMatFlow)
        self.pushButton_normalize_probs.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_normalize_probs.setObjectName(_fromUtf8("pushButton_normalize_probs"))
        self.horizontalLayout_3.addWidget(self.pushButton_normalize_probs)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.checkBox_are_materials_substitude = QtGui.QCheckBox(Dialog_EditMatFlow)
        self.checkBox_are_materials_substitude.setMaximumSize(QtCore.QSize(154, 17))
        self.checkBox_are_materials_substitude.setObjectName(_fromUtf8("checkBox_are_materials_substitude"))
        self.horizontalLayout_3.addWidget(self.checkBox_are_materials_substitude)
        self.pushButton_add_material = QtGui.QPushButton(Dialog_EditMatFlow)
        self.pushButton_add_material.setObjectName(_fromUtf8("pushButton_add_material"))
        self.horizontalLayout_3.addWidget(self.pushButton_add_material)
        self.pushButton_delete_material = QtGui.QPushButton(Dialog_EditMatFlow)
        self.pushButton_delete_material.setObjectName(_fromUtf8("pushButton_delete_material"))
        self.horizontalLayout_3.addWidget(self.pushButton_delete_material)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView_materials_and_probs = QtGui.QTableView(Dialog_EditMatFlow)
        self.tableView_materials_and_probs.setObjectName(_fromUtf8("tableView_materials_and_probs"))
        self.verticalLayout.addWidget(self.tableView_materials_and_probs)
        self.line_2 = QtGui.QFrame(Dialog_EditMatFlow)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_EditMatFlow)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_EditMatFlow)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_EditMatFlow.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_EditMatFlow.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_EditMatFlow)

    def retranslateUi(self, Dialog_EditMatFlow):
        Dialog_EditMatFlow.setWindowTitle(_translate("Dialog_EditMatFlow", "Dialog", None))
        self.label.setText(_translate("Dialog_EditMatFlow", "Группа товаров", None))
        self.lineEdit_cons_volume_mean.setToolTip(_translate("Dialog_EditMatFlow", "<html><head/><body><p>Ожидаемый объём потребления - сколько единиц товара клиент берет за 1 заказ.</p></body></html>", None))
        self.label_2.setText(_translate("Dialog_EditMatFlow", "Объем потребления", None))
        self.label_9.setText(_translate("Dialog_EditMatFlow", "дн.", None))
        self.label_4.setText(_translate("Dialog_EditMatFlow", "+/-", None))
        self.label_5.setText(_translate("Dialog_EditMatFlow", "%", None))
        self.lineEdit_cons_vol_dev.setToolTip(_translate("Dialog_EditMatFlow", "<html><head/><body><p>С вероятностью 68% реальное потребление окажется в этом интервале. Пожалуйста, указывается реалистичное значение.</p></body></html>", None))
        self.label_MeasUnit.setText(_translate("Dialog_EditMatFlow", "Ед. изм", None))
        self.label_6.setText(_translate("Dialog_EditMatFlow", "кал. дн.", None))
        self.label_3.setText(_translate("Dialog_EditMatFlow", "Через каждые", None))
        self.lineEdit_cons_period_mean.setToolTip(_translate("Dialog_EditMatFlow", "<html><head/><body><p>Ожидаемая периодичность потребления - раз в сколько календарных дней клиент размещает заказ.</p></body></html>", None))
        self.lineEdit_cons_period_std.setToolTip(_translate("Dialog_EditMatFlow", "<html><head/><body><p>С вероятностью 68% клиент разместит заказ в этом интервале относительно следующей даты заказа. Пожалуйста, обратите внимание на то, чтобы этот интервал не был слишком оптимистичным.</p></body></html>", None))
        self.label_7.setText(_translate("Dialog_EditMatFlow", "+/-", None))
        self.dateEdit_NextExpectedOrder.setToolTip(_translate("Dialog_EditMatFlow", "<html><head/><body><p>Прогноз даты следующего заказа. Оценивается автоматически при каждом новом размещенном заказе в 1С, но для крупных заказов и в случае задержки заказов, лучше указывать эту дату вручную, пообщавшись с клиентом.</p></body></html>", None))
        self.label_10.setText(_translate("Dialog_EditMatFlow", "Следующая отгрузка:", None))
        self.label_8.setText(_translate("Dialog_EditMatFlow", "Доля \"прямых\" (экономных) поставок", None))
        self.label_12.setText(_translate("Dialog_EditMatFlow", "Склад (дороже)", None))
        self.horizontalSlider_EconomyShare.setToolTip(_translate("Dialog_EditMatFlow", "<html><head/><body><p>Если слайдер полностью влево, то клиенту нужны только срочные поставки со склада. Если слайдер полностью вправо, то клиенту нужны только экономичные поставки напрямую.</p></body></html>", None))
        self.label_11.setText(_translate("Dialog_EditMatFlow", "Напрямую (экономия)", None))
        self.pushButton_EstimateStatistics.setToolTip(_translate("Dialog_EditMatFlow", "Оценить объёмы, частоту потребления и вероятности выбора материалов по статистике отгрузок и заказов.", None))
        self.pushButton_EstimateStatistics.setText(_translate("Dialog_EditMatFlow", "Оценить по статистике", None))
        self.pushButton_down_025.setText(_translate("Dialog_EditMatFlow", "Снизить на 25%", None))
        self.pushButton_up_025.setText(_translate("Dialog_EditMatFlow", "Повысить на 25%", None))
        self.pushButton_normalize_probs.setToolTip(_translate("Dialog_EditMatFlow", "Нормализовать вероятности к процентам (можно не нажимать)", None))
        self.pushButton_normalize_probs.setText(_translate("Dialog_EditMatFlow", "~", None))
        self.checkBox_are_materials_substitude.setToolTip(_translate("Dialog_EditMatFlow", "Являются ли товары из списка ниже взаимозаменяемыми для клиента (если нет одного в наличии, возьмёт другое) ?", None))
        self.checkBox_are_materials_substitude.setText(_translate("Dialog_EditMatFlow", "Товары взаимозаменяемы?", None))
        self.pushButton_add_material.setText(_translate("Dialog_EditMatFlow", "Добавить", None))
        self.pushButton_delete_material.setText(_translate("Dialog_EditMatFlow", "Удалить", None))
        self.tableView_materials_and_probs.setToolTip(_translate("Dialog_EditMatFlow", "Распределение вероятностей выбора конкретного материала. Если материалы взаимозаменяемы, существенной роли не играет.", None))

