# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\THE_PROJ_Refactor\ui\DialogCrm_EditContact.ui'
#
# Created: Sun Dec 28 19:40:47 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogCrm_EditContact(object):
    def setupUi(self, DialogCrm_EditContact):
        DialogCrm_EditContact.setObjectName(_fromUtf8("DialogCrm_EditContact"))
        DialogCrm_EditContact.resize(725, 497)
        self.verticalLayout_4 = QtGui.QVBoxLayout(DialogCrm_EditContact)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(DialogCrm_EditContact)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_name = QtGui.QLineEdit(DialogCrm_EditContact)
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.horizontalLayout_3.addWidget(self.lineEdit_name)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(DialogCrm_EditContact)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_job = QtGui.QLineEdit(DialogCrm_EditContact)
        self.lineEdit_job.setObjectName(_fromUtf8("lineEdit_job"))
        self.horizontalLayout_5.addWidget(self.lineEdit_job)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.comboBox_company = QtGui.QComboBox(DialogCrm_EditContact)
        self.comboBox_company.setObjectName(_fromUtf8("comboBox_company"))
        self.gridLayout.addWidget(self.comboBox_company, 1, 1, 1, 1)
        self.checkBox_is_person = QtGui.QCheckBox(DialogCrm_EditContact)
        self.checkBox_is_person.setObjectName(_fromUtf8("checkBox_is_person"))
        self.gridLayout.addWidget(self.checkBox_is_person, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableView_contact_info = QtGui.QTableView(DialogCrm_EditContact)
        self.tableView_contact_info.setObjectName(_fromUtf8("tableView_contact_info"))
        self.horizontalLayout_2.addWidget(self.tableView_contact_info)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_add_email = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_email.setObjectName(_fromUtf8("pushButton_add_email"))
        self.verticalLayout.addWidget(self.pushButton_add_email)
        self.pushButton_add_cell_work = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_cell_work.setObjectName(_fromUtf8("pushButton_add_cell_work"))
        self.verticalLayout.addWidget(self.pushButton_add_cell_work)
        self.pushButton_add_cell_personal = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_cell_personal.setObjectName(_fromUtf8("pushButton_add_cell_personal"))
        self.verticalLayout.addWidget(self.pushButton_add_cell_personal)
        self.pushButton_add_phone = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_phone.setObjectName(_fromUtf8("pushButton_add_phone"))
        self.verticalLayout.addWidget(self.pushButton_add_phone)
        self.pushButton_add_skype = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_skype.setObjectName(_fromUtf8("pushButton_add_skype"))
        self.verticalLayout.addWidget(self.pushButton_add_skype)
        self.pushButton_add_birthday = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_birthday.setObjectName(_fromUtf8("pushButton_add_birthday"))
        self.verticalLayout.addWidget(self.pushButton_add_birthday)
        self.pushButton_add_website = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_website.setObjectName(_fromUtf8("pushButton_add_website"))
        self.verticalLayout.addWidget(self.pushButton_add_website)
        self.pushButton_add_address_post = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_address_post.setObjectName(_fromUtf8("pushButton_add_address_post"))
        self.verticalLayout.addWidget(self.pushButton_add_address_post)
        self.pushButton_add_address_fact = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_address_fact.setObjectName(_fromUtf8("pushButton_add_address_fact"))
        self.verticalLayout.addWidget(self.pushButton_add_address_fact)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_add_row = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_add_row.setObjectName(_fromUtf8("pushButton_add_row"))
        self.horizontalLayout.addWidget(self.pushButton_add_row)
        self.pushButton_delete_row = QtGui.QPushButton(DialogCrm_EditContact)
        self.pushButton_delete_row.setObjectName(_fromUtf8("pushButton_delete_row"))
        self.horizontalLayout.addWidget(self.pushButton_delete_row)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(DialogCrm_EditContact)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.plainTextEdit_additional_info = QtGui.QPlainTextEdit(DialogCrm_EditContact)
        self.plainTextEdit_additional_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit_additional_info.setObjectName(_fromUtf8("plainTextEdit_additional_info"))
        self.verticalLayout_3.addWidget(self.plainTextEdit_additional_info)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(DialogCrm_EditContact)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.checkBox_SubsPrices = QtGui.QCheckBox(DialogCrm_EditContact)
        self.checkBox_SubsPrices.setObjectName(_fromUtf8("checkBox_SubsPrices"))
        self.verticalLayout_2.addWidget(self.checkBox_SubsPrices)
        self.checkBox_SubsLogistics = QtGui.QCheckBox(DialogCrm_EditContact)
        self.checkBox_SubsLogistics.setObjectName(_fromUtf8("checkBox_SubsLogistics"))
        self.verticalLayout_2.addWidget(self.checkBox_SubsLogistics)
        self.checkBox_SubsPayments = QtGui.QCheckBox(DialogCrm_EditContact)
        self.checkBox_SubsPayments.setObjectName(_fromUtf8("checkBox_SubsPayments"))
        self.verticalLayout_2.addWidget(self.checkBox_SubsPayments)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(DialogCrm_EditContact)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(DialogCrm_EditContact)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogCrm_EditContact.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogCrm_EditContact.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogCrm_EditContact)

    def retranslateUi(self, DialogCrm_EditContact):
        DialogCrm_EditContact.setWindowTitle(_translate("DialogCrm_EditContact", "Dialog", None))
        self.label_2.setText(_translate("DialogCrm_EditContact", "ФИО", None))
        self.label_3.setText(_translate("DialogCrm_EditContact", "Должность", None))
        self.checkBox_is_person.setText(_translate("DialogCrm_EditContact", "Физическое лицо", None))
        self.pushButton_add_email.setText(_translate("DialogCrm_EditContact", "+Email", None))
        self.pushButton_add_cell_work.setText(_translate("DialogCrm_EditContact", "+Мобильный", None))
        self.pushButton_add_cell_personal.setText(_translate("DialogCrm_EditContact", "+Мобильный личный", None))
        self.pushButton_add_phone.setText(_translate("DialogCrm_EditContact", "+Городской", None))
        self.pushButton_add_skype.setText(_translate("DialogCrm_EditContact", "+Skype", None))
        self.pushButton_add_birthday.setText(_translate("DialogCrm_EditContact", "+День рождения", None))
        self.pushButton_add_website.setText(_translate("DialogCrm_EditContact", "+Сайт", None))
        self.pushButton_add_address_post.setText(_translate("DialogCrm_EditContact", "+Почтовый адрес", None))
        self.pushButton_add_address_fact.setText(_translate("DialogCrm_EditContact", "+Физический адрес", None))
        self.pushButton_add_row.setText(_translate("DialogCrm_EditContact", "+", None))
        self.pushButton_delete_row.setText(_translate("DialogCrm_EditContact", "-", None))
        self.label_4.setText(_translate("DialogCrm_EditContact", "Роль / особенности / как дозвониться", None))
        self.label_5.setText(_translate("DialogCrm_EditContact", "Рассылки:", None))
        self.checkBox_SubsPrices.setText(_translate("DialogCrm_EditContact", "Цены", None))
        self.checkBox_SubsLogistics.setText(_translate("DialogCrm_EditContact", "Логистика", None))
        self.checkBox_SubsPayments.setText(_translate("DialogCrm_EditContact", "Оплаты", None))

