# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\THE_PROJ_V1_01\ui\DialogCrm_EditSimpleRecord.ui'
#
# Created: Thu Feb 05 19:07:14 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogCrm_EditSimpleRecord(object):
    def setupUi(self, DialogCrm_EditSimpleRecord):
        DialogCrm_EditSimpleRecord.setObjectName(_fromUtf8("DialogCrm_EditSimpleRecord"))
        DialogCrm_EditSimpleRecord.resize(748, 478)
        self.verticalLayout = QtGui.QVBoxLayout(DialogCrm_EditSimpleRecord)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_addhashtag = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_addhashtag.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_addhashtag.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addhashtag.setFont(font)
        self.pushButton_addhashtag.setObjectName(_fromUtf8("pushButton_addhashtag"))
        self.horizontalLayout_2.addWidget(self.pushButton_addhashtag)
        self.line_3 = QtGui.QFrame(DialogCrm_EditSimpleRecord)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.pushButton_bold = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_bold.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_bold.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_bold.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bold.setIcon(icon)
        self.pushButton_bold.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_bold.setObjectName(_fromUtf8("pushButton_bold"))
        self.horizontalLayout_2.addWidget(self.pushButton_bold)
        self.pushButton_italic = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_italic.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_italic.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_italic.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/italic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_italic.setIcon(icon1)
        self.pushButton_italic.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_italic.setObjectName(_fromUtf8("pushButton_italic"))
        self.horizontalLayout_2.addWidget(self.pushButton_italic)
        self.pushButton_underline = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_underline.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_underline.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_underline.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/underline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_underline.setIcon(icon2)
        self.pushButton_underline.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_underline.setObjectName(_fromUtf8("pushButton_underline"))
        self.horizontalLayout_2.addWidget(self.pushButton_underline)
        self.line = QtGui.QFrame(DialogCrm_EditSimpleRecord)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.pushButton_bulletList = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_bulletList.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_bulletList.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_bulletList.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/bullet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bulletList.setIcon(icon3)
        self.pushButton_bulletList.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_bulletList.setObjectName(_fromUtf8("pushButton_bulletList"))
        self.horizontalLayout_2.addWidget(self.pushButton_bulletList)
        self.pushButton_numberList = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_numberList.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_numberList.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_numberList.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/number.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_numberList.setIcon(icon4)
        self.pushButton_numberList.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_numberList.setObjectName(_fromUtf8("pushButton_numberList"))
        self.horizontalLayout_2.addWidget(self.pushButton_numberList)
        self.pushButton_table = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_table.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_table.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_table.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_table.setIcon(icon5)
        self.pushButton_table.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_table.setObjectName(_fromUtf8("pushButton_table"))
        self.horizontalLayout_2.addWidget(self.pushButton_table)
        self.line_2 = QtGui.QFrame(DialogCrm_EditSimpleRecord)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.pushButton_undo = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_undo.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_undo.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_undo.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_undo.setIcon(icon6)
        self.pushButton_undo.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_undo.setObjectName(_fromUtf8("pushButton_undo"))
        self.horizontalLayout_2.addWidget(self.pushButton_undo)
        self.pushButton_redo = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_redo.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_redo.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_redo.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_redo.setIcon(icon7)
        self.pushButton_redo.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_redo.setObjectName(_fromUtf8("pushButton_redo"))
        self.horizontalLayout_2.addWidget(self.pushButton_redo)
        spacerItem = QtGui.QSpacerItem(118, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_date_added = QtGui.QLabel(DialogCrm_EditSimpleRecord)
        self.label_date_added.setObjectName(_fromUtf8("label_date_added"))
        self.horizontalLayout.addWidget(self.label_date_added)
        self.lineEdit_headline = QtGui.QLineEdit(DialogCrm_EditSimpleRecord)
        self.lineEdit_headline.setObjectName(_fromUtf8("lineEdit_headline"))
        self.horizontalLayout.addWidget(self.lineEdit_headline)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_for_textedit = QtGui.QHBoxLayout()
        self.horizontalLayout_for_textedit.setObjectName(_fromUtf8("horizontalLayout_for_textedit"))
        self.verticalLayout.addLayout(self.horizontalLayout_for_textedit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_print = QtGui.QPushButton(DialogCrm_EditSimpleRecord)
        self.pushButton_print.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_print.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_print.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_print.setIcon(icon8)
        self.pushButton_print.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_print.setObjectName(_fromUtf8("pushButton_print"))
        self.horizontalLayout_3.addWidget(self.pushButton_print)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(DialogCrm_EditSimpleRecord)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(DialogCrm_EditSimpleRecord)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogCrm_EditSimpleRecord.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogCrm_EditSimpleRecord.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogCrm_EditSimpleRecord)

    def retranslateUi(self, DialogCrm_EditSimpleRecord):
        DialogCrm_EditSimpleRecord.setWindowTitle(_translate("DialogCrm_EditSimpleRecord", "Dialog", None))
        self.pushButton_addhashtag.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Вставить hashtag (Ctrl + H)", None))
        self.pushButton_addhashtag.setText(_translate("DialogCrm_EditSimpleRecord", "#", None))
        self.pushButton_addhashtag.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+H", None))
        self.pushButton_bold.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Жирным (Ctrl + B)", None))
        self.pushButton_bold.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+B", None))
        self.pushButton_italic.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Курсив (Ctrl + I)", None))
        self.pushButton_italic.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+I", None))
        self.pushButton_underline.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Подчеркнуть (Ctrl + U)", None))
        self.pushButton_underline.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+U", None))
        self.pushButton_bulletList.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Список (Ctrl + .)", None))
        self.pushButton_bulletList.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+.", None))
        self.pushButton_numberList.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Нум. список (Ctrl + /)", None))
        self.pushButton_numberList.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+/", None))
        self.pushButton_table.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Таблица (Ctrl + T)", None))
        self.pushButton_table.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+T", None))
        self.pushButton_undo.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Отменить (Ctrl + Z)", None))
        self.pushButton_undo.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+Z", None))
        self.pushButton_redo.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Сделать обратно (Ctrl + Y)", None))
        self.pushButton_redo.setShortcut(_translate("DialogCrm_EditSimpleRecord", "Ctrl+Y", None))
        self.label_date_added.setText(_translate("DialogCrm_EditSimpleRecord", "TextLabel", None))
        self.pushButton_print.setToolTip(_translate("DialogCrm_EditSimpleRecord", "Печать", None))

import qrc_crm_texteditor
