# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Code\SimpleBusiness\ui\Dialog_EditPrice.ui'
#
# Created: Thu Jan 28 00:02:12 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_EditClientPrice(object):
    def setupUi(self, Dialog_EditClientPrice):
        Dialog_EditClientPrice.setObjectName(_fromUtf8("Dialog_EditClientPrice"))
        Dialog_EditClientPrice.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_EditClientPrice.resize(510, 507)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_EditClientPrice.sizePolicy().hasHeightForWidth())
        Dialog_EditClientPrice.setSizePolicy(sizePolicy)
        Dialog_EditClientPrice.setMinimumSize(QtCore.QSize(510, 0))
        Dialog_EditClientPrice.setMaximumSize(QtCore.QSize(1000, 544))
        Dialog_EditClientPrice.setModal(True)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog_EditClientPrice)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_material = QtGui.QComboBox(Dialog_EditClientPrice)
        self.comboBox_material.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_material.setAutoFillBackground(False)
        self.comboBox_material.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox_material.setEditable(False)
        self.comboBox_material.setMaxVisibleItems(20)
        self.comboBox_material.setObjectName(_fromUtf8("comboBox_material"))
        self.horizontalLayout.addWidget(self.comboBox_material)
        self.checkBox_is_for_group = QtGui.QCheckBox(Dialog_EditClientPrice)
        self.checkBox_is_for_group.setMaximumSize(QtCore.QSize(70, 16777215))
        self.checkBox_is_for_group.setObjectName(_fromUtf8("checkBox_is_for_group"))
        self.horizontalLayout.addWidget(self.checkBox_is_for_group)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog_EditClientPrice)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog_EditClientPrice)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_price = QtGui.QLineEdit(Dialog_EditClientPrice)
        self.lineEdit_price.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_price.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_price.setToolTip(_fromUtf8(""))
        self.lineEdit_price.setMaxLength(255)
        self.lineEdit_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_price.setObjectName(_fromUtf8("lineEdit_price"))
        self.horizontalLayout_2.addWidget(self.lineEdit_price)
        self.label_currency_name = QtGui.QLabel(Dialog_EditClientPrice)
        self.label_currency_name.setObjectName(_fromUtf8("label_currency_name"))
        self.horizontalLayout_2.addWidget(self.label_currency_name)
        self.label_17 = QtGui.QLabel(Dialog_EditClientPrice)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_units = QtGui.QLabel(Dialog_EditClientPrice)
        self.label_units.setObjectName(_fromUtf8("label_units"))
        self.horizontalLayout_2.addWidget(self.label_units)
        self.checkBox_IsAgentScheme = QtGui.QCheckBox(Dialog_EditClientPrice)
        self.checkBox_IsAgentScheme.setObjectName(_fromUtf8("checkBox_IsAgentScheme"))
        self.horizontalLayout_2.addWidget(self.checkBox_IsAgentScheme)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog_EditClientPrice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(1000, 100))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBox_payment_terms = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_payment_terms.sizePolicy().hasHeightForWidth())
        self.comboBox_payment_terms.setSizePolicy(sizePolicy)
        self.comboBox_payment_terms.setObjectName(_fromUtf8("comboBox_payment_terms"))
        self.horizontalLayout_3.addWidget(self.comboBox_payment_terms)
        self.checkBox_IsFactoring = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_IsFactoring.setObjectName(_fromUtf8("checkBox_IsFactoring"))
        self.horizontalLayout_3.addWidget(self.checkBox_IsFactoring)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.label_PayTermDescription = QtGui.QLabel(self.groupBox_2)
        self.label_PayTermDescription.setObjectName(_fromUtf8("label_PayTermDescription"))
        self.verticalLayout_5.addWidget(self.label_PayTermDescription)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Dialog_EditClientPrice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 114))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_EstimateClientLimits = QtGui.QPushButton(self.groupBox)
        self.pushButton_EstimateClientLimits.setObjectName(_fromUtf8("pushButton_EstimateClientLimits"))
        self.horizontalLayout_7.addWidget(self.pushButton_EstimateClientLimits)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setWhatsThis(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_ClPrMinOQ = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ClPrMinOQ.setWhatsThis(_fromUtf8(""))
        self.lineEdit_ClPrMinOQ.setObjectName(_fromUtf8("lineEdit_ClPrMinOQ"))
        self.horizontalLayout_7.addWidget(self.lineEdit_ClPrMinOQ)
        self.label_units_2 = QtGui.QLabel(self.groupBox)
        self.label_units_2.setObjectName(_fromUtf8("label_units_2"))
        self.horizontalLayout_7.addWidget(self.label_units_2)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setWhatsThis(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.lineEdit_ClPrMinOS = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ClPrMinOS.setWhatsThis(_fromUtf8(""))
        self.lineEdit_ClPrMinOS.setObjectName(_fromUtf8("lineEdit_ClPrMinOS"))
        self.horizontalLayout_7.addWidget(self.lineEdit_ClPrMinOS)
        self.label_currency_name_2 = QtGui.QLabel(self.groupBox)
        self.label_currency_name_2.setObjectName(_fromUtf8("label_currency_name_2"))
        self.horizontalLayout_7.addWidget(self.label_currency_name_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_IsValidBetweenDates = QtGui.QCheckBox(self.groupBox)
        self.checkBox_IsValidBetweenDates.setObjectName(_fromUtf8("checkBox_IsValidBetweenDates"))
        self.horizontalLayout_4.addWidget(self.checkBox_IsValidBetweenDates)
        self.dateEdit_PriceValidFrom = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_PriceValidFrom.setObjectName(_fromUtf8("dateEdit_PriceValidFrom"))
        self.horizontalLayout_4.addWidget(self.dateEdit_PriceValidFrom)
        self.dateEdit_PriceValidTill = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_PriceValidTill.setObjectName(_fromUtf8("dateEdit_PriceValidTill"))
        self.horizontalLayout_4.addWidget(self.dateEdit_PriceValidTill)
        self.pushButton_LimitToWeek = QtGui.QPushButton(self.groupBox)
        self.pushButton_LimitToWeek.setWhatsThis(_fromUtf8(""))
        self.pushButton_LimitToWeek.setObjectName(_fromUtf8("pushButton_LimitToWeek"))
        self.horizontalLayout_4.addWidget(self.pushButton_LimitToWeek)
        self.pushButton_LimitToMonth = QtGui.QPushButton(self.groupBox)
        self.pushButton_LimitToMonth.setWhatsThis(_fromUtf8(""))
        self.pushButton_LimitToMonth.setObjectName(_fromUtf8("pushButton_LimitToMonth"))
        self.horizontalLayout_4.addWidget(self.pushButton_LimitToMonth)
        self.pushButton_LimitToQuater = QtGui.QPushButton(self.groupBox)
        self.pushButton_LimitToQuater.setWhatsThis(_fromUtf8(""))
        self.pushButton_LimitToQuater.setObjectName(_fromUtf8("pushButton_LimitToQuater"))
        self.horizontalLayout_4.addWidget(self.pushButton_LimitToQuater)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_ClientPriceDetails = QtGui.QGroupBox(Dialog_EditClientPrice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ClientPriceDetails.sizePolicy().hasHeightForWidth())
        self.groupBox_ClientPriceDetails.setSizePolicy(sizePolicy)
        self.groupBox_ClientPriceDetails.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_ClientPriceDetails.setMaximumSize(QtCore.QSize(16777215, 131))
        self.groupBox_ClientPriceDetails.setObjectName(_fromUtf8("groupBox_ClientPriceDetails"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_ClientPriceDetails)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_ClPrPerOrderOnly = QtGui.QCheckBox(self.groupBox_ClientPriceDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ClPrPerOrderOnly.sizePolicy().hasHeightForWidth())
        self.checkBox_ClPrPerOrderOnly.setSizePolicy(sizePolicy)
        self.checkBox_ClPrPerOrderOnly.setObjectName(_fromUtf8("checkBox_ClPrPerOrderOnly"))
        self.horizontalLayout_6.addWidget(self.checkBox_ClPrPerOrderOnly)
        self.checkBox_ClPrIsShipmentTo = QtGui.QCheckBox(self.groupBox_ClientPriceDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ClPrIsShipmentTo.sizePolicy().hasHeightForWidth())
        self.checkBox_ClPrIsShipmentTo.setSizePolicy(sizePolicy)
        self.checkBox_ClPrIsShipmentTo.setObjectName(_fromUtf8("checkBox_ClPrIsShipmentTo"))
        self.horizontalLayout_6.addWidget(self.checkBox_ClPrIsShipmentTo)
        self.lineEdit_ClPrPlaceOfShipment = QtGui.QLineEdit(self.groupBox_ClientPriceDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ClPrPlaceOfShipment.sizePolicy().hasHeightForWidth())
        self.lineEdit_ClPrPlaceOfShipment.setSizePolicy(sizePolicy)
        self.lineEdit_ClPrPlaceOfShipment.setObjectName(_fromUtf8("lineEdit_ClPrPlaceOfShipment"))
        self.horizontalLayout_6.addWidget(self.lineEdit_ClPrPlaceOfShipment)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_ClientPriceDetails)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_ClPrOrderFulfilmentTerm = QtGui.QLineEdit(self.groupBox_ClientPriceDetails)
        self.lineEdit_ClPrOrderFulfilmentTerm.setObjectName(_fromUtf8("lineEdit_ClPrOrderFulfilmentTerm"))
        self.horizontalLayout_5.addWidget(self.lineEdit_ClPrOrderFulfilmentTerm)
        self.label_9 = QtGui.QLabel(self.groupBox_ClientPriceDetails)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.groupBox_ClientPriceDetails)
        self.groupBox_SupplierPriceDetails = QtGui.QGroupBox(Dialog_EditClientPrice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_SupplierPriceDetails.sizePolicy().hasHeightForWidth())
        self.groupBox_SupplierPriceDetails.setSizePolicy(sizePolicy)
        self.groupBox_SupplierPriceDetails.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_SupplierPriceDetails.setMaximumSize(QtCore.QSize(16777215, 121))
        self.groupBox_SupplierPriceDetails.setObjectName(_fromUtf8("groupBox_SupplierPriceDetails"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_SupplierPriceDetails)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_19 = QtGui.QLabel(self.groupBox_SupplierPriceDetails)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_11.addWidget(self.label_19)
        self.lineEdit_SupPrIncotermsPlace = QtGui.QLineEdit(self.groupBox_SupplierPriceDetails)
        self.lineEdit_SupPrIncotermsPlace.setWhatsThis(_fromUtf8(""))
        self.lineEdit_SupPrIncotermsPlace.setObjectName(_fromUtf8("lineEdit_SupPrIncotermsPlace"))
        self.horizontalLayout_11.addWidget(self.lineEdit_SupPrIncotermsPlace)
        self.label_2 = QtGui.QLabel(self.groupBox_SupplierPriceDetails)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.lineEdit_LeadTime = QtGui.QLineEdit(self.groupBox_SupplierPriceDetails)
        self.lineEdit_LeadTime.setObjectName(_fromUtf8("lineEdit_LeadTime"))
        self.horizontalLayout_11.addWidget(self.lineEdit_LeadTime)
        self.label_5 = QtGui.QLabel(self.groupBox_SupplierPriceDetails)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_SupPrIsForSpecClient = QtGui.QCheckBox(self.groupBox_SupplierPriceDetails)
        self.checkBox_SupPrIsForSpecClient.setWhatsThis(_fromUtf8(""))
        self.checkBox_SupPrIsForSpecClient.setObjectName(_fromUtf8("checkBox_SupPrIsForSpecClient"))
        self.horizontalLayout_9.addWidget(self.checkBox_SupPrIsForSpecClient)
        self.comboBox_SupPrForWichClient = QtGui.QComboBox(self.groupBox_SupplierPriceDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SupPrForWichClient.sizePolicy().hasHeightForWidth())
        self.comboBox_SupPrForWichClient.setSizePolicy(sizePolicy)
        self.comboBox_SupPrForWichClient.setWhatsThis(_fromUtf8(""))
        self.comboBox_SupPrForWichClient.setObjectName(_fromUtf8("comboBox_SupPrForWichClient"))
        self.horizontalLayout_9.addWidget(self.comboBox_SupPrForWichClient)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.groupBox_SupplierPriceDetails)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_SpecialCond = QtGui.QCheckBox(Dialog_EditClientPrice)
        self.checkBox_SpecialCond.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_SpecialCond.setObjectName(_fromUtf8("checkBox_SpecialCond"))
        self.horizontalLayout_10.addWidget(self.checkBox_SpecialCond)
        self.plainTextEdit_special_conditions = QtGui.QPlainTextEdit(Dialog_EditClientPrice)
        self.plainTextEdit_special_conditions.setMinimumSize(QtCore.QSize(0, 30))
        self.plainTextEdit_special_conditions.setObjectName(_fromUtf8("plainTextEdit_special_conditions"))
        self.horizontalLayout_10.addWidget(self.plainTextEdit_special_conditions)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.line_8 = QtGui.QFrame(Dialog_EditClientPrice)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_4.addWidget(self.line_8)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_EditClientPrice)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_8.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Dialog_EditClientPrice)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_EditClientPrice.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_EditClientPrice.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_EditClientPrice)
        Dialog_EditClientPrice.setTabOrder(self.comboBox_material, self.checkBox_is_for_group)
        Dialog_EditClientPrice.setTabOrder(self.checkBox_is_for_group, self.lineEdit_price)
        Dialog_EditClientPrice.setTabOrder(self.lineEdit_price, self.dateEdit_PriceValidFrom)
        Dialog_EditClientPrice.setTabOrder(self.dateEdit_PriceValidFrom, self.dateEdit_PriceValidTill)
        Dialog_EditClientPrice.setTabOrder(self.dateEdit_PriceValidTill, self.comboBox_payment_terms)
        Dialog_EditClientPrice.setTabOrder(self.comboBox_payment_terms, self.checkBox_ClPrIsShipmentTo)
        Dialog_EditClientPrice.setTabOrder(self.checkBox_ClPrIsShipmentTo, self.lineEdit_ClPrPlaceOfShipment)
        Dialog_EditClientPrice.setTabOrder(self.lineEdit_ClPrPlaceOfShipment, self.lineEdit_ClPrOrderFulfilmentTerm)
        Dialog_EditClientPrice.setTabOrder(self.lineEdit_ClPrOrderFulfilmentTerm, self.lineEdit_ClPrMinOQ)
        Dialog_EditClientPrice.setTabOrder(self.lineEdit_ClPrMinOQ, self.lineEdit_ClPrMinOS)
        Dialog_EditClientPrice.setTabOrder(self.lineEdit_ClPrMinOS, self.lineEdit_SupPrIncotermsPlace)
        Dialog_EditClientPrice.setTabOrder(self.lineEdit_SupPrIncotermsPlace, self.plainTextEdit_special_conditions)

    def retranslateUi(self, Dialog_EditClientPrice):
        Dialog_EditClientPrice.setWindowTitle(_translate("Dialog_EditClientPrice", "Edit price", None))
        self.checkBox_is_for_group.setToolTip(_translate("Dialog_EditClientPrice", "Можете задать цену на группу, а затем на исключения из правила", None))
        self.checkBox_is_for_group.setText(_translate("Dialog_EditClientPrice", "группа", None))
        self.label_3.setText(_translate("Dialog_EditClientPrice", "Цена", None))
        self.label.setText(_translate("Dialog_EditClientPrice", "Товар", None))
        self.label_currency_name.setText(_translate("Dialog_EditClientPrice", "currency name", None))
        self.label_17.setText(_translate("Dialog_EditClientPrice", "за", None))
        self.label_units.setText(_translate("Dialog_EditClientPrice", "Units", None))
        self.checkBox_IsAgentScheme.setText(_translate("Dialog_EditClientPrice", "Агентская схема", None))
        self.groupBox_2.setTitle(_translate("Dialog_EditClientPrice", "Условия оплаты", None))
        self.checkBox_IsFactoring.setToolTip(_translate("Dialog_EditClientPrice", "Если расчеты предложены по факторингу", None))
        self.checkBox_IsFactoring.setText(_translate("Dialog_EditClientPrice", "Факторинг", None))
        self.label_PayTermDescription.setText(_translate("Dialog_EditClientPrice", "Описание условий оплаты", None))
        self.groupBox.setTitle(_translate("Dialog_EditClientPrice", "Ограничения", None))
        self.pushButton_EstimateClientLimits.setToolTip(_translate("Dialog_EditClientPrice", "Подобрать ограничения и срок, исходя из запросов клиента", None))
        self.pushButton_EstimateClientLimits.setText(_translate("Dialog_EditClientPrice", "Подобрать", None))
        self.label_4.setToolTip(_translate("Dialog_EditClientPrice", "Минимальный объем заказа", None))
        self.label_4.setText(_translate("Dialog_EditClientPrice", "MOQ", None))
        self.lineEdit_ClPrMinOQ.setToolTip(_translate("Dialog_EditClientPrice", "Минимальный объем заказа", None))
        self.label_units_2.setText(_translate("Dialog_EditClientPrice", "Units", None))
        self.label_11.setToolTip(_translate("Dialog_EditClientPrice", "Минимальная сумма заказа", None))
        self.label_11.setText(_translate("Dialog_EditClientPrice", "MOS", None))
        self.lineEdit_ClPrMinOS.setToolTip(_translate("Dialog_EditClientPrice", "Минимальная сумма заказа", None))
        self.label_currency_name_2.setText(_translate("Dialog_EditClientPrice", "CcyUnits", None))
        self.checkBox_IsValidBetweenDates.setText(_translate("Dialog_EditClientPrice", "Срок", None))
        self.dateEdit_PriceValidFrom.setWhatsThis(_translate("Dialog_EditClientPrice", "Первая возможная дата отгрузки по такой цене", None))
        self.dateEdit_PriceValidTill.setWhatsThis(_translate("Dialog_EditClientPrice", "Последняя возможная дата отгрузки по такой цене (дальше - пересмотр)", None))
        self.pushButton_LimitToWeek.setToolTip(_translate("Dialog_EditClientPrice", "Горячее предложение", None))
        self.pushButton_LimitToWeek.setText(_translate("Dialog_EditClientPrice", "Неделя", None))
        self.pushButton_LimitToMonth.setToolTip(_translate("Dialog_EditClientPrice", "Пересмотреть через месяц", None))
        self.pushButton_LimitToMonth.setText(_translate("Dialog_EditClientPrice", "Месяц", None))
        self.pushButton_LimitToQuater.setToolTip(_translate("Dialog_EditClientPrice", "Установить на 90 дней", None))
        self.pushButton_LimitToQuater.setText(_translate("Dialog_EditClientPrice", "Квартал", None))
        self.groupBox_ClientPriceDetails.setTitle(_translate("Dialog_EditClientPrice", "Условия поставки", None))
        self.checkBox_ClPrPerOrderOnly.setToolTip(_translate("Dialog_EditClientPrice", "Случай, когда не обещаем хранить на складе", None))
        self.checkBox_ClPrPerOrderOnly.setText(_translate("Dialog_EditClientPrice", "Только под заказ", None))
        self.checkBox_ClPrIsShipmentTo.setText(_translate("Dialog_EditClientPrice", "Доставка", None))
        self.lineEdit_ClPrPlaceOfShipment.setToolTip(_translate("Dialog_EditClientPrice", "Место доставки", None))
        self.label_8.setText(_translate("Dialog_EditClientPrice", "Отгрузка в течение", None))
        self.lineEdit_ClPrOrderFulfilmentTerm.setToolTip(_translate("Dialog_EditClientPrice", "Если срок не выполнен, заказ уйдёт", None))
        self.label_9.setText(_translate("Dialog_EditClientPrice", "к. дней с момента получения заказа", None))
        self.groupBox_SupplierPriceDetails.setTitle(_translate("Dialog_EditClientPrice", "Условия поставки", None))
        self.label_19.setText(_translate("Dialog_EditClientPrice", "Incoterms", None))
        self.lineEdit_SupPrIncotermsPlace.setToolTip(_translate("Dialog_EditClientPrice", "Место отгрузки по указанным условиям", None))
        self.label_2.setText(_translate("Dialog_EditClientPrice", "Lead time", None))
        self.label_5.setText(_translate("Dialog_EditClientPrice", "days", None))
        self.checkBox_SupPrIsForSpecClient.setToolTip(_translate("Dialog_EditClientPrice", "Цена предложена только под заказ клиента", None))
        self.checkBox_SupPrIsForSpecClient.setText(_translate("Dialog_EditClientPrice", "Только под прямой заказ клиента", None))
        self.comboBox_SupPrForWichClient.setToolTip(_translate("Dialog_EditClientPrice", "Первые в списке - те, кто может потреблять товар", None))
        self.checkBox_SpecialCond.setText(_translate("Dialog_EditClientPrice", "Специальные условия", None))
        self.plainTextEdit_special_conditions.setToolTip(_translate("Dialog_EditClientPrice", "Любые иные условия", None))

