# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\THE_PROJ\ui\DlgEditSalesOppotunity.ui'
#
# Created: Sat Feb 21 22:58:24 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_EditSalesOppotunity(object):
    def setupUi(self, Dialog_EditSalesOppotunity):
        Dialog_EditSalesOppotunity.setObjectName(_fromUtf8("Dialog_EditSalesOppotunity"))
        Dialog_EditSalesOppotunity.resize(425, 269)
        Dialog_EditSalesOppotunity.setMaximumSize(QtCore.QSize(682, 269))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_EditSalesOppotunity)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_material_type = QtGui.QComboBox(Dialog_EditSalesOppotunity)
        self.comboBox_material_type.setObjectName(_fromUtf8("comboBox_material_type"))
        self.gridLayout.addWidget(self.comboBox_material_type, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalSlider_surelevel = QtGui.QSlider(Dialog_EditSalesOppotunity)
        self.horizontalSlider_surelevel.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_surelevel.setObjectName(_fromUtf8("horizontalSlider_surelevel"))
        self.horizontalLayout_5.addWidget(self.horizontalSlider_surelevel)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalSlider_succprob = QtGui.QSlider(Dialog_EditSalesOppotunity)
        self.horizontalSlider_succprob.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_succprob.setObjectName(_fromUtf8("horizontalSlider_succprob"))
        self.horizontalLayout_2.addWidget(self.horizontalSlider_succprob)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.dateEdit_start_early = QtGui.QDateEdit(Dialog_EditSalesOppotunity)
        self.dateEdit_start_early.setObjectName(_fromUtf8("dateEdit_start_early"))
        self.horizontalLayout.addWidget(self.dateEdit_start_early)
        self.label_11 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.dateEdit_start_late = QtGui.QDateEdit(Dialog_EditSalesOppotunity)
        self.dateEdit_start_late.setObjectName(_fromUtf8("dateEdit_start_late"))
        self.horizontalLayout.addWidget(self.dateEdit_start_late)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_expected_periodicity = QtGui.QLineEdit(Dialog_EditSalesOppotunity)
        self.lineEdit_expected_periodicity.setObjectName(_fromUtf8("lineEdit_expected_periodicity"))
        self.horizontalLayout_4.addWidget(self.lineEdit_expected_periodicity)
        self.label_8 = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit_expected_qtty = QtGui.QLineEdit(Dialog_EditSalesOppotunity)
        self.lineEdit_expected_qtty.setObjectName(_fromUtf8("lineEdit_expected_qtty"))
        self.horizontalLayout_3.addWidget(self.lineEdit_expected_qtty)
        self.label_meas_unit = QtGui.QLabel(Dialog_EditSalesOppotunity)
        self.label_meas_unit.setObjectName(_fromUtf8("label_meas_unit"))
        self.horizontalLayout_3.addWidget(self.label_meas_unit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.checkBox_instock_promise = QtGui.QCheckBox(Dialog_EditSalesOppotunity)
        self.checkBox_instock_promise.setObjectName(_fromUtf8("checkBox_instock_promise"))
        self.gridLayout.addWidget(self.checkBox_instock_promise, 6, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_changedates_to_m = QtGui.QPushButton(Dialog_EditSalesOppotunity)
        self.pushButton_changedates_to_m.setObjectName(_fromUtf8("pushButton_changedates_to_m"))
        self.horizontalLayout_7.addWidget(self.pushButton_changedates_to_m)
        self.pushButton_changedates_to_q = QtGui.QPushButton(Dialog_EditSalesOppotunity)
        self.pushButton_changedates_to_q.setObjectName(_fromUtf8("pushButton_changedates_to_q"))
        self.horizontalLayout_7.addWidget(self.pushButton_changedates_to_q)
        self.pushButton_changedates_to_hy = QtGui.QPushButton(Dialog_EditSalesOppotunity)
        self.pushButton_changedates_to_hy.setObjectName(_fromUtf8("pushButton_changedates_to_hy"))
        self.horizontalLayout_7.addWidget(self.pushButton_changedates_to_hy)
        self.pushButton_changedates_to_y = QtGui.QPushButton(Dialog_EditSalesOppotunity)
        self.pushButton_changedates_to_y.setObjectName(_fromUtf8("pushButton_changedates_to_y"))
        self.horizontalLayout_7.addWidget(self.pushButton_changedates_to_y)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_EditSalesOppotunity)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog_EditSalesOppotunity)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_EditSalesOppotunity.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_EditSalesOppotunity.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_EditSalesOppotunity)

    def retranslateUi(self, Dialog_EditSalesOppotunity):
        Dialog_EditSalesOppotunity.setWindowTitle(_translate("Dialog_EditSalesOppotunity", "Dialog", None))
        self.label_3.setText(_translate("Dialog_EditSalesOppotunity", "Уверенность в показаниях", None))
        self.label_5.setText(_translate("Dialog_EditSalesOppotunity", "Ожидаемая периодичность", None))
        self.label_4.setText(_translate("Dialog_EditSalesOppotunity", "Ожидаемый объём заказа", None))
        self.label_2.setText(_translate("Dialog_EditSalesOppotunity", "Вероятность успеха", None))
        self.label_6.setText(_translate("Dialog_EditSalesOppotunity", "Первая возможная отгрузка", None))
        self.label.setText(_translate("Dialog_EditSalesOppotunity", "Группа товаров", None))
        self.label_10.setText(_translate("Dialog_EditSalesOppotunity", "между", None))
        self.label_11.setText(_translate("Dialog_EditSalesOppotunity", "и", None))
        self.label_7.setText(_translate("Dialog_EditSalesOppotunity", "каждые", None))
        self.label_8.setText(_translate("Dialog_EditSalesOppotunity", "к. дн.", None))
        self.label_meas_unit.setText(_translate("Dialog_EditSalesOppotunity", "Ед. Изм.", None))
        self.checkBox_instock_promise.setText(_translate("Dialog_EditSalesOppotunity", "Обещаем держать на складе", None))
        self.pushButton_changedates_to_m.setText(_translate("Dialog_EditSalesOppotunity", "месяц", None))
        self.pushButton_changedates_to_q.setText(_translate("Dialog_EditSalesOppotunity", "квартал", None))
        self.pushButton_changedates_to_hy.setText(_translate("Dialog_EditSalesOppotunity", "полгода", None))
        self.pushButton_changedates_to_y.setText(_translate("Dialog_EditSalesOppotunity", "год", None))

