# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ilua\SimpleBusiness\SimpleBusiness\ui\ModernMainWindow_v2.ui'
#
# Created: Tue Dec 29 15:54:25 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowModern(object):
    def setupUi(self, MainWindowModern):
        MainWindowModern.setObjectName(_fromUtf8("MainWindowModern"))
        MainWindowModern.setWindowModality(QtCore.Qt.NonModal)
        MainWindowModern.resize(1262, 822)
        MainWindowModern.setDocumentMode(False)
        MainWindowModern.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindowModern)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.Global_tabs = QtGui.QTabWidget(self.centralwidget)
        self.Global_tabs.setEnabled(True)
        self.Global_tabs.setTabPosition(QtGui.QTabWidget.North)
        self.Global_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.Global_tabs.setDocumentMode(False)
        self.Global_tabs.setObjectName(_fromUtf8("Global_tabs"))
        self.tab_Clients = QtGui.QWidget()
        self.tab_Clients.setObjectName(_fromUtf8("tab_Clients"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_Clients)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit_ClientFilter = QtGui.QLineEdit(self.tab_Clients)
        self.lineEdit_ClientFilter.setObjectName(_fromUtf8("lineEdit_ClientFilter"))
        self.verticalLayout.addWidget(self.lineEdit_ClientFilter)
        self.listView_ClientList = QtGui.QListView(self.tab_Clients)
        self.listView_ClientList.setObjectName(_fromUtf8("listView_ClientList"))
        self.verticalLayout.addWidget(self.listView_ClientList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_DeleteClient = QtGui.QPushButton(self.tab_Clients)
        self.pushButton_DeleteClient.setObjectName(_fromUtf8("pushButton_DeleteClient"))
        self.horizontalLayout.addWidget(self.pushButton_DeleteClient)
        self.pushButton_NewClient = QtGui.QPushButton(self.tab_Clients)
        self.pushButton_NewClient.setObjectName(_fromUtf8("pushButton_NewClient"))
        self.horizontalLayout.addWidget(self.pushButton_NewClient)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.Global_tabs.addTab(self.tab_Clients, _fromUtf8(""))
        self.tab_KnBase = QtGui.QWidget()
        self.tab_KnBase.setObjectName(_fromUtf8("tab_KnBase"))
        self.lineEdit_KnBase_Search = QtGui.QLineEdit(self.tab_KnBase)
        self.lineEdit_KnBase_Search.setGeometry(QtCore.QRect(10, 10, 551, 20))
        self.lineEdit_KnBase_Search.setObjectName(_fromUtf8("lineEdit_KnBase_Search"))
        self.pushButton = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton.setGeometry(QtCore.QRect(580, 10, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.widget = QtGui.QWidget(self.tab_KnBase)
        self.widget.setGeometry(QtCore.QRect(10, 90, 1311, 691))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.pushButton_KnBaseEmptyNote = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_KnBaseEmptyNote.setGeometry(QtCore.QRect(700, 10, 621, 41))
        self.pushButton_KnBaseEmptyNote.setObjectName(_fromUtf8("pushButton_KnBaseEmptyNote"))
        self.Global_tabs.addTab(self.tab_KnBase, _fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.Global_tabs)
        MainWindowModern.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowModern)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1262, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.AdminMenu = QtGui.QMenu(self.menubar)
        self.AdminMenu.setObjectName(_fromUtf8("AdminMenu"))
        self.FastAddMenu = QtGui.QMenu(self.menubar)
        self.FastAddMenu.setAcceptDrops(True)
        self.FastAddMenu.setObjectName(_fromUtf8("FastAddMenu"))
        MainWindowModern.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowModern)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowModern.setStatusBar(self.statusbar)
        self.action_Run_Simulate = QtGui.QAction(MainWindowModern)
        self.action_Run_Simulate.setObjectName(_fromUtf8("action_Run_Simulate"))
        self.action_Synhronize_xm_with_db = QtGui.QAction(MainWindowModern)
        self.action_Synhronize_xm_with_db.setObjectName(_fromUtf8("action_Synhronize_xm_with_db"))
        self.action_upload_budget_csv = QtGui.QAction(MainWindowModern)
        self.action_upload_budget_csv.setObjectName(_fromUtf8("action_upload_budget_csv"))
        self.action_2 = QtGui.QAction(MainWindowModern)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindowModern)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(MainWindowModern)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(MainWindowModern)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(MainWindowModern)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_fast_NewContact = QtGui.QAction(MainWindowModern)
        self.action_fast_NewContact.setObjectName(_fromUtf8("action_fast_NewContact"))
        self.action = QtGui.QAction(MainWindowModern)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_AddFastNote = QtGui.QAction(MainWindowModern)
        self.action_AddFastNote.setObjectName(_fromUtf8("action_AddFastNote"))
        self.action_AddNewContact = QtGui.QAction(MainWindowModern)
        self.action_AddNewContact.setObjectName(_fromUtf8("action_AddNewContact"))
        self.action_7 = QtGui.QAction(MainWindowModern)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_8 = QtGui.QAction(MainWindowModern)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.action_AddNewCP = QtGui.QAction(MainWindowModern)
        self.action_AddNewCP.setObjectName(_fromUtf8("action_AddNewCP"))
        self.AdminMenu.addAction(self.action_Run_Simulate)
        self.AdminMenu.addAction(self.action_Synhronize_xm_with_db)
        self.AdminMenu.addAction(self.action_upload_budget_csv)
        self.FastAddMenu.addAction(self.action_AddFastNote)
        self.FastAddMenu.addSeparator()
        self.FastAddMenu.addAction(self.action_AddNewContact)
        self.FastAddMenu.addAction(self.action_AddNewCP)
        self.menubar.addAction(self.FastAddMenu.menuAction())
        self.menubar.addAction(self.AdminMenu.menuAction())

        self.retranslateUi(MainWindowModern)
        self.Global_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowModern)

    def retranslateUi(self, MainWindowModern):
        MainWindowModern.setWindowTitle(_translate("MainWindowModern", "Simple Business ", None))
        self.pushButton_DeleteClient.setText(_translate("MainWindowModern", "- Удалить", None))
        self.pushButton_NewClient.setText(_translate("MainWindowModern", "+ Новый", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_Clients), _translate("MainWindowModern", "Клиенты и поставщики", None))
        self.pushButton.setText(_translate("MainWindowModern", "PushButton", None))
        self.pushButton_KnBaseEmptyNote.setText(_translate("MainWindowModern", "+ Новая заметка", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_KnBase), _translate("MainWindowModern", "База знаний", None))
        self.AdminMenu.setTitle(_translate("MainWindowModern", "Администрирование", None))
        self.FastAddMenu.setTitle(_translate("MainWindowModern", "Добавить", None))
        self.action_Run_Simulate.setText(_translate("MainWindowModern", "Запуск симуляции", None))
        self.action_Synhronize_xm_with_db.setText(_translate("MainWindowModern", "Загрузить из 1С", None))
        self.action_upload_budget_csv.setText(_translate("MainWindowModern", "Выгрузить в 1С", None))
        self.action_2.setText(_translate("MainWindowModern", "#ЗапросТовара", None))
        self.action_3.setText(_translate("MainWindowModern", "#Бюджет", None))
        self.action_4.setText(_translate("MainWindowModern", "#Офер", None))
        self.action_5.setText(_translate("MainWindowModern", "#Прайс", None))
        self.action_6.setText(_translate("MainWindowModern", "#Беседа", None))
        self.action_fast_NewContact.setText(_translate("MainWindowModern", "Новый контакт", None))
        self.action.setText(_translate("MainWindowModern", "Заметка", None))
        self.action_AddFastNote.setText(_translate("MainWindowModern", "+ Быстрая заметка", None))
        self.action_AddNewContact.setText(_translate("MainWindowModern", "+ Контакт", None))
        self.action_7.setText(_translate("MainWindowModern", "+ Клиент", None))
        self.action_8.setText(_translate("MainWindowModern", "+ Поставщик", None))
        self.action_AddNewCP.setText(_translate("MainWindowModern", "+ Контрагент", None))

