# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\THE_PROJ\ui\MainWindow.ui'
#
# Created: Fri Apr 10 21:57:55 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(924, 643)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.Global_tabs = QtGui.QTabWidget(self.centralwidget)
        self.Global_tabs.setEnabled(True)
        self.Global_tabs.setTabPosition(QtGui.QTabWidget.North)
        self.Global_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.Global_tabs.setDocumentMode(False)
        self.Global_tabs.setObjectName(_fromUtf8("Global_tabs"))
        self.tab_Clients = QtGui.QWidget()
        self.tab_Clients.setObjectName(_fromUtf8("tab_Clients"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.tab_Clients)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lineEdit_find_counterparty = QtGui.QLineEdit(self.tab_Clients)
        self.lineEdit_find_counterparty.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_find_counterparty.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_find_counterparty.setObjectName(_fromUtf8("lineEdit_find_counterparty"))
        self.verticalLayout_7.addWidget(self.lineEdit_find_counterparty)
        self.treeView_counterparties = QtGui.QTreeView(self.tab_Clients)
        self.treeView_counterparties.setMinimumSize(QtCore.QSize(300, 0))
        self.treeView_counterparties.setMaximumSize(QtCore.QSize(300, 16777215))
        self.treeView_counterparties.setObjectName(_fromUtf8("treeView_counterparties"))
        self.verticalLayout_7.addWidget(self.treeView_counterparties)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.pushButton_NewCounterparty = QtGui.QPushButton(self.tab_Clients)
        self.pushButton_NewCounterparty.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_NewCounterparty.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_NewCounterparty.setObjectName(_fromUtf8("pushButton_NewCounterparty"))
        self.horizontalLayout_24.addWidget(self.pushButton_NewCounterparty)
        self.pushButton_EditCounterparty = QtGui.QPushButton(self.tab_Clients)
        self.pushButton_EditCounterparty.setEnabled(True)
        self.pushButton_EditCounterparty.setObjectName(_fromUtf8("pushButton_EditCounterparty"))
        self.horizontalLayout_24.addWidget(self.pushButton_EditCounterparty)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26.addLayout(self.verticalLayout_7)
        self.tab_counterparty_settings = QtGui.QTabWidget(self.tab_Clients)
        self.tab_counterparty_settings.setTabPosition(QtGui.QTabWidget.West)
        self.tab_counterparty_settings.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_counterparty_settings.setObjectName(_fromUtf8("tab_counterparty_settings"))
        self.tab_CPOverview = QtGui.QWidget()
        self.tab_CPOverview.setObjectName(_fromUtf8("tab_CPOverview"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_CPOverview)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.pushButton_ToCPKnBase = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_ToCPKnBase.setObjectName(_fromUtf8("pushButton_ToCPKnBase"))
        self.horizontalLayout_33.addWidget(self.pushButton_ToCPKnBase)
        self.pushButton_ToCPContatcts = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_ToCPContatcts.setObjectName(_fromUtf8("pushButton_ToCPContatcts"))
        self.horizontalLayout_33.addWidget(self.pushButton_ToCPContatcts)
        self.pushButton_ToCPForecast = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_ToCPForecast.setObjectName(_fromUtf8("pushButton_ToCPForecast"))
        self.horizontalLayout_33.addWidget(self.pushButton_ToCPForecast)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem)
        self.pushButton_HashCPblank = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_HashCPblank.setObjectName(_fromUtf8("pushButton_HashCPblank"))
        self.horizontalLayout_33.addWidget(self.pushButton_HashCPblank)
        self.verticalLayout_4.addLayout(self.horizontalLayout_33)
        self.text_client_report = QtGui.QTextBrowser(self.tab_CPOverview)
        self.text_client_report.setObjectName(_fromUtf8("text_client_report"))
        self.verticalLayout_4.addWidget(self.text_client_report)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_add_contact_to_company = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_add_contact_to_company.setEnabled(True)
        self.pushButton_add_contact_to_company.setObjectName(_fromUtf8("pushButton_add_contact_to_company"))
        self.horizontalLayout_5.addWidget(self.pushButton_add_contact_to_company)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pushButton_PrintCPCard = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_PrintCPCard.setEnabled(True)
        self.pushButton_PrintCPCard.setObjectName(_fromUtf8("pushButton_PrintCPCard"))
        self.horizontalLayout_5.addWidget(self.pushButton_PrintCPCard)
        self.pushButton_SendCPCard = QtGui.QPushButton(self.tab_CPOverview)
        self.pushButton_SendCPCard.setEnabled(True)
        self.pushButton_SendCPCard.setObjectName(_fromUtf8("pushButton_SendCPCard"))
        self.horizontalLayout_5.addWidget(self.pushButton_SendCPCard)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tab_counterparty_settings.addTab(self.tab_CPOverview, _fromUtf8(""))
        self.tab_ClientConsumption = QtGui.QWidget()
        self.tab_ClientConsumption.setObjectName(_fromUtf8("tab_ClientConsumption"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_ClientConsumption)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.pushButton_ToCPKnBase_Consumption = QtGui.QPushButton(self.tab_ClientConsumption)
        self.pushButton_ToCPKnBase_Consumption.setObjectName(_fromUtf8("pushButton_ToCPKnBase_Consumption"))
        self.horizontalLayout_32.addWidget(self.pushButton_ToCPKnBase_Consumption)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem2)
        self.pushButton_HashBudget = QtGui.QPushButton(self.tab_ClientConsumption)
        self.pushButton_HashBudget.setObjectName(_fromUtf8("pushButton_HashBudget"))
        self.horizontalLayout_32.addWidget(self.pushButton_HashBudget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.tableView_client_material_flows = QtGui.QTableView(self.tab_ClientConsumption)
        self.tableView_client_material_flows.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_client_material_flows.sizePolicy().hasHeightForWidth())
        self.tableView_client_material_flows.setSizePolicy(sizePolicy)
        self.tableView_client_material_flows.setLineWidth(1)
        self.tableView_client_material_flows.setObjectName(_fromUtf8("tableView_client_material_flows"))
        self.verticalLayout_3.addWidget(self.tableView_client_material_flows)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.but_estimate_ship_stats = QtGui.QPushButton(self.tab_ClientConsumption)
        self.but_estimate_ship_stats.setObjectName(_fromUtf8("but_estimate_ship_stats"))
        self.horizontalLayout_2.addWidget(self.but_estimate_ship_stats)
        self.pushButton_AddMaterialFlowToClient = QtGui.QPushButton(self.tab_ClientConsumption)
        self.pushButton_AddMaterialFlowToClient.setMaximumSize(QtCore.QSize(76, 16777215))
        self.pushButton_AddMaterialFlowToClient.setObjectName(_fromUtf8("pushButton_AddMaterialFlowToClient"))
        self.horizontalLayout_2.addWidget(self.pushButton_AddMaterialFlowToClient)
        self.pushButton_EditMaterialFlowFromClient = QtGui.QPushButton(self.tab_ClientConsumption)
        self.pushButton_EditMaterialFlowFromClient.setMaximumSize(QtCore.QSize(76, 16777215))
        self.pushButton_EditMaterialFlowFromClient.setObjectName(_fromUtf8("pushButton_EditMaterialFlowFromClient"))
        self.horizontalLayout_2.addWidget(self.pushButton_EditMaterialFlowFromClient)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_DeleteMaterialFlowFromClient = QtGui.QPushButton(self.tab_ClientConsumption)
        self.pushButton_DeleteMaterialFlowFromClient.setMaximumSize(QtCore.QSize(76, 16777215))
        self.pushButton_DeleteMaterialFlowFromClient.setObjectName(_fromUtf8("pushButton_DeleteMaterialFlowFromClient"))
        self.horizontalLayout_2.addWidget(self.pushButton_DeleteMaterialFlowFromClient)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tab_counterparty_settings.addTab(self.tab_ClientConsumption, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.pushButton_ToCPKnBase_Consumption_2 = QtGui.QPushButton(self.tab)
        self.pushButton_ToCPKnBase_Consumption_2.setObjectName(_fromUtf8("pushButton_ToCPKnBase_Consumption_2"))
        self.horizontalLayout_35.addWidget(self.pushButton_ToCPKnBase_Consumption_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem4)
        self.pushButton_HashClientDevelopment = QtGui.QPushButton(self.tab)
        self.pushButton_HashClientDevelopment.setObjectName(_fromUtf8("pushButton_HashClientDevelopment"))
        self.horizontalLayout_35.addWidget(self.pushButton_HashClientDevelopment)
        self.verticalLayout_8.addLayout(self.horizontalLayout_35)
        self.tableView_client_oppotunities = QtGui.QTableView(self.tab)
        self.tableView_client_oppotunities.setObjectName(_fromUtf8("tableView_client_oppotunities"))
        self.verticalLayout_8.addWidget(self.tableView_client_oppotunities)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_create_matflow = QtGui.QPushButton(self.tab)
        self.pushButton_create_matflow.setObjectName(_fromUtf8("pushButton_create_matflow"))
        self.horizontalLayout.addWidget(self.pushButton_create_matflow)
        self.pushButton_AddOppToClient = QtGui.QPushButton(self.tab)
        self.pushButton_AddOppToClient.setEnabled(True)
        self.pushButton_AddOppToClient.setObjectName(_fromUtf8("pushButton_AddOppToClient"))
        self.horizontalLayout.addWidget(self.pushButton_AddOppToClient)
        self.pushButton_EditOppClient = QtGui.QPushButton(self.tab)
        self.pushButton_EditOppClient.setEnabled(True)
        self.pushButton_EditOppClient.setObjectName(_fromUtf8("pushButton_EditOppClient"))
        self.horizontalLayout.addWidget(self.pushButton_EditOppClient)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton_DeleteOppClient = QtGui.QPushButton(self.tab)
        self.pushButton_DeleteOppClient.setEnabled(True)
        self.pushButton_DeleteOppClient.setObjectName(_fromUtf8("pushButton_DeleteOppClient"))
        self.horizontalLayout.addWidget(self.pushButton_DeleteOppClient)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.tab_counterparty_settings.addTab(self.tab, _fromUtf8(""))
        self.tab_ClientOffers = QtGui.QWidget()
        self.tab_ClientOffers.setObjectName(_fromUtf8("tab_ClientOffers"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_ClientOffers)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_ToCPKnBase_offers = QtGui.QPushButton(self.tab_ClientOffers)
        self.pushButton_ToCPKnBase_offers.setObjectName(_fromUtf8("pushButton_ToCPKnBase_offers"))
        self.horizontalLayout_8.addWidget(self.pushButton_ToCPKnBase_offers)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.pushButton_HashClientOffer = QtGui.QPushButton(self.tab_ClientOffers)
        self.pushButton_HashClientOffer.setObjectName(_fromUtf8("pushButton_HashClientOffer"))
        self.horizontalLayout_8.addWidget(self.pushButton_HashClientOffer)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tableView_prices = QtGui.QTableView(self.tab_ClientOffers)
        self.tableView_prices.setObjectName(_fromUtf8("tableView_prices"))
        self.verticalLayout_5.addWidget(self.tableView_prices)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_AddPriceToClient = QtGui.QPushButton(self.tab_ClientOffers)
        self.pushButton_AddPriceToClient.setObjectName(_fromUtf8("pushButton_AddPriceToClient"))
        self.horizontalLayout_3.addWidget(self.pushButton_AddPriceToClient)
        self.pushButton_EditPriceToClient = QtGui.QPushButton(self.tab_ClientOffers)
        self.pushButton_EditPriceToClient.setObjectName(_fromUtf8("pushButton_EditPriceToClient"))
        self.horizontalLayout_3.addWidget(self.pushButton_EditPriceToClient)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pushButton_DeletePriceFromClient = QtGui.QPushButton(self.tab_ClientOffers)
        self.pushButton_DeletePriceFromClient.setObjectName(_fromUtf8("pushButton_DeletePriceFromClient"))
        self.horizontalLayout_3.addWidget(self.pushButton_DeletePriceFromClient)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.tab_counterparty_settings.addTab(self.tab_ClientOffers, _fromUtf8(""))
        self.tab_SupplierPrices = QtGui.QWidget()
        self.tab_SupplierPrices.setObjectName(_fromUtf8("tab_SupplierPrices"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab_SupplierPrices)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.pushButton_ToCPKnBase_prices = QtGui.QPushButton(self.tab_SupplierPrices)
        self.pushButton_ToCPKnBase_prices.setObjectName(_fromUtf8("pushButton_ToCPKnBase_prices"))
        self.horizontalLayout_31.addWidget(self.pushButton_ToCPKnBase_prices)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem8)
        self.pushButton_HashSupplierPrice = QtGui.QPushButton(self.tab_SupplierPrices)
        self.pushButton_HashSupplierPrice.setObjectName(_fromUtf8("pushButton_HashSupplierPrice"))
        self.horizontalLayout_31.addWidget(self.pushButton_HashSupplierPrice)
        self.verticalLayout_19.addLayout(self.horizontalLayout_31)
        self.tableView_SupplierPrices = QtGui.QTableView(self.tab_SupplierPrices)
        self.tableView_SupplierPrices.setObjectName(_fromUtf8("tableView_SupplierPrices"))
        self.verticalLayout_19.addWidget(self.tableView_SupplierPrices)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.pushButton_AddPriceToSupplier = QtGui.QPushButton(self.tab_SupplierPrices)
        self.pushButton_AddPriceToSupplier.setObjectName(_fromUtf8("pushButton_AddPriceToSupplier"))
        self.horizontalLayout_21.addWidget(self.pushButton_AddPriceToSupplier)
        self.pushButton_EditPriceToSupplier = QtGui.QPushButton(self.tab_SupplierPrices)
        self.pushButton_EditPriceToSupplier.setObjectName(_fromUtf8("pushButton_EditPriceToSupplier"))
        self.horizontalLayout_21.addWidget(self.pushButton_EditPriceToSupplier)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.pushButton_DeletePriceFromSupplier = QtGui.QPushButton(self.tab_SupplierPrices)
        self.pushButton_DeletePriceFromSupplier.setObjectName(_fromUtf8("pushButton_DeletePriceFromSupplier"))
        self.horizontalLayout_21.addWidget(self.pushButton_DeletePriceFromSupplier)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        self.tab_counterparty_settings.addTab(self.tab_SupplierPrices, _fromUtf8(""))
        self.horizontalLayout_26.addWidget(self.tab_counterparty_settings)
        self.Global_tabs.addTab(self.tab_Clients, _fromUtf8(""))
        self.tab_Contacts = QtGui.QWidget()
        self.tab_Contacts.setObjectName(_fromUtf8("tab_Contacts"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.tab_Contacts)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.lineEdit_search_contact = QtGui.QLineEdit(self.tab_Contacts)
        self.lineEdit_search_contact.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_search_contact.setObjectName(_fromUtf8("lineEdit_search_contact"))
        self.verticalLayout_15.addWidget(self.lineEdit_search_contact)
        self.listView_contacts = QtGui.QListView(self.tab_Contacts)
        self.listView_contacts.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listView_contacts.setObjectName(_fromUtf8("listView_contacts"))
        self.verticalLayout_15.addWidget(self.listView_contacts)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.pushButton_add_contact = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_add_contact.setObjectName(_fromUtf8("pushButton_add_contact"))
        self.horizontalLayout_22.addWidget(self.pushButton_add_contact)
        self.pushButton_edit_contact = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_edit_contact.setObjectName(_fromUtf8("pushButton_edit_contact"))
        self.horizontalLayout_22.addWidget(self.pushButton_edit_contact)
        spacerItem10 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem10)
        self.pushButton_delete_contact = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_delete_contact.setObjectName(_fromUtf8("pushButton_delete_contact"))
        self.horizontalLayout_22.addWidget(self.pushButton_delete_contact)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25.addLayout(self.verticalLayout_15)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.pushButton_HashClientMeetingContact = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_HashClientMeetingContact.setEnabled(True)
        self.pushButton_HashClientMeetingContact.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_HashClientMeetingContact.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_HashClientMeetingContact.setFont(font)
        self.pushButton_HashClientMeetingContact.setObjectName(_fromUtf8("pushButton_HashClientMeetingContact"))
        self.horizontalLayout_30.addWidget(self.pushButton_HashClientMeetingContact)
        self.pushButton_WriteALetterToContact = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_WriteALetterToContact.setEnabled(True)
        self.pushButton_WriteALetterToContact.setObjectName(_fromUtf8("pushButton_WriteALetterToContact"))
        self.horizontalLayout_30.addWidget(self.pushButton_WriteALetterToContact)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem11)
        self.verticalLayout_18.addLayout(self.horizontalLayout_30)
        self.textBrowser_contact_data = QtGui.QTextBrowser(self.tab_Contacts)
        self.textBrowser_contact_data.setObjectName(_fromUtf8("textBrowser_contact_data"))
        self.verticalLayout_18.addWidget(self.textBrowser_contact_data)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem12)
        self.pushButton_PrintContactInfo = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_PrintContactInfo.setEnabled(True)
        self.pushButton_PrintContactInfo.setObjectName(_fromUtf8("pushButton_PrintContactInfo"))
        self.horizontalLayout_29.addWidget(self.pushButton_PrintContactInfo)
        self.pushButton_SendContactInfo = QtGui.QPushButton(self.tab_Contacts)
        self.pushButton_SendContactInfo.setEnabled(True)
        self.pushButton_SendContactInfo.setObjectName(_fromUtf8("pushButton_SendContactInfo"))
        self.horizontalLayout_29.addWidget(self.pushButton_SendContactInfo)
        self.verticalLayout_18.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_25.addLayout(self.verticalLayout_18)
        self.Global_tabs.addTab(self.tab_Contacts, _fromUtf8(""))
        self.tab_KnBase = QtGui.QWidget()
        self.tab_KnBase.setObjectName(_fromUtf8("tab_KnBase"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.tab_KnBase)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.pushButton_KnBaseEmptyNote = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_KnBaseEmptyNote.setObjectName(_fromUtf8("pushButton_KnBaseEmptyNote"))
        self.verticalLayout_22.addWidget(self.pushButton_KnBaseEmptyNote)
        self.tabWidget_KnBaseSource = QtGui.QTabWidget(self.tab_KnBase)
        self.tabWidget_KnBaseSource.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget_KnBaseSource.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabWidget_KnBaseSource.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget_KnBaseSource.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_KnBaseSource.setObjectName(_fromUtf8("tabWidget_KnBaseSource"))
        self.tab_tag_search = QtGui.QWidget()
        self.tab_tag_search.setObjectName(_fromUtf8("tab_tag_search"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_tag_search)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.lineEdit_KnBaseSearchHahtag = QtGui.QLineEdit(self.tab_tag_search)
        self.lineEdit_KnBaseSearchHahtag.setObjectName(_fromUtf8("lineEdit_KnBaseSearchHahtag"))
        self.horizontalLayout_27.addWidget(self.lineEdit_KnBaseSearchHahtag)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.listView_KnBaseHashtags = QtGui.QListView(self.tab_tag_search)
        self.listView_KnBaseHashtags.setObjectName(_fromUtf8("listView_KnBaseHashtags"))
        self.verticalLayout_16.addWidget(self.listView_KnBaseHashtags)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.pushButton_RenameHashtag = QtGui.QPushButton(self.tab_tag_search)
        self.pushButton_RenameHashtag.setEnabled(True)
        self.pushButton_RenameHashtag.setObjectName(_fromUtf8("pushButton_RenameHashtag"))
        self.horizontalLayout_28.addWidget(self.pushButton_RenameHashtag)
        self.pushButton_SwitchFromHashtagToRecords = QtGui.QPushButton(self.tab_tag_search)
        self.pushButton_SwitchFromHashtagToRecords.setObjectName(_fromUtf8("pushButton_SwitchFromHashtagToRecords"))
        self.horizontalLayout_28.addWidget(self.pushButton_SwitchFromHashtagToRecords)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        self.tabWidget_KnBaseSource.addTab(self.tab_tag_search, _fromUtf8(""))
        self.tab_record_search = QtGui.QWidget()
        self.tab_record_search.setObjectName(_fromUtf8("tab_record_search"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_record_search)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lineEdit_SearchHashKnBase = QtGui.QLineEdit(self.tab_record_search)
        self.lineEdit_SearchHashKnBase.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_SearchHashKnBase.setMaximumSize(QtCore.QSize(1000, 1000))
        self.lineEdit_SearchHashKnBase.setObjectName(_fromUtf8("lineEdit_SearchHashKnBase"))
        self.horizontalLayout_9.addWidget(self.lineEdit_SearchHashKnBase)
        self.pushButton_KnBaseRunRecordSearch = QtGui.QPushButton(self.tab_record_search)
        self.pushButton_KnBaseRunRecordSearch.setObjectName(_fromUtf8("pushButton_KnBaseRunRecordSearch"))
        self.horizontalLayout_9.addWidget(self.pushButton_KnBaseRunRecordSearch)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.listView_KnBase = QtGui.QListView(self.tab_record_search)
        self.listView_KnBase.setMaximumSize(QtCore.QSize(380, 16777215))
        self.listView_KnBase.setObjectName(_fromUtf8("listView_KnBase"))
        self.verticalLayout_6.addWidget(self.listView_KnBase)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_AddNoteKnBase = QtGui.QPushButton(self.tab_record_search)
        self.pushButton_AddNoteKnBase.setObjectName(_fromUtf8("pushButton_AddNoteKnBase"))
        self.horizontalLayout_10.addWidget(self.pushButton_AddNoteKnBase)
        self.pushButton_EditNoteKnBase = QtGui.QPushButton(self.tab_record_search)
        self.pushButton_EditNoteKnBase.setObjectName(_fromUtf8("pushButton_EditNoteKnBase"))
        self.horizontalLayout_10.addWidget(self.pushButton_EditNoteKnBase)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.pushButton_DeleteNoteKnBase = QtGui.QPushButton(self.tab_record_search)
        self.pushButton_DeleteNoteKnBase.setObjectName(_fromUtf8("pushButton_DeleteNoteKnBase"))
        self.horizontalLayout_10.addWidget(self.pushButton_DeleteNoteKnBase)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.tabWidget_KnBaseSource.addTab(self.tab_record_search, _fromUtf8(""))
        self.verticalLayout_22.addWidget(self.tabWidget_KnBaseSource)
        self.horizontalLayout_34.addLayout(self.verticalLayout_22)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit_smart_hashtag_search = QtGui.QLineEdit(self.tab_KnBase)
        self.lineEdit_smart_hashtag_search.setObjectName(_fromUtf8("lineEdit_smart_hashtag_search"))
        self.horizontalLayout_7.addWidget(self.lineEdit_smart_hashtag_search)
        self.pushButton_update_themefilt = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_update_themefilt.setMaximumSize(QtCore.QSize(200, 100))
        self.pushButton_update_themefilt.setObjectName(_fromUtf8("pushButton_update_themefilt"))
        self.horizontalLayout_7.addWidget(self.pushButton_update_themefilt)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_textBrowser_KnBase = QtGui.QHBoxLayout()
        self.horizontalLayout_textBrowser_KnBase.setObjectName(_fromUtf8("horizontalLayout_textBrowser_KnBase"))
        self.verticalLayout_17.addLayout(self.horizontalLayout_textBrowser_KnBase)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem14)
        self.pushButton_PrintKnBaseView = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_PrintKnBaseView.setEnabled(True)
        self.pushButton_PrintKnBaseView.setObjectName(_fromUtf8("pushButton_PrintKnBaseView"))
        self.horizontalLayout_20.addWidget(self.pushButton_PrintKnBaseView)
        self.pushButton_EmailKnBaseView = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_EmailKnBaseView.setEnabled(True)
        self.pushButton_EmailKnBaseView.setObjectName(_fromUtf8("pushButton_EmailKnBaseView"))
        self.horizontalLayout_20.addWidget(self.pushButton_EmailKnBaseView)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_34.addLayout(self.verticalLayout_17)
        self.Global_tabs.addTab(self.tab_KnBase, _fromUtf8(""))
        self.tab_AllProcesses = QtGui.QWidget()
        self.tab_AllProcesses.setObjectName(_fromUtf8("tab_AllProcesses"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.tab_AllProcesses)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.lineEdit_search_process = QtGui.QLineEdit(self.tab_AllProcesses)
        self.lineEdit_search_process.setObjectName(_fromUtf8("lineEdit_search_process"))
        self.verticalLayout_13.addWidget(self.lineEdit_search_process)
        self.project_tree_view = QtGui.QTreeView(self.tab_AllProcesses)
        self.project_tree_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.project_tree_view.setObjectName(_fromUtf8("project_tree_view"))
        self.verticalLayout_13.addWidget(self.project_tree_view)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.but_projects_delete = QtGui.QPushButton(self.tab_AllProcesses)
        self.but_projects_delete.setObjectName(_fromUtf8("but_projects_delete"))
        self.horizontalLayout_4.addWidget(self.but_projects_delete)
        self.but_projects_new = QtGui.QPushButton(self.tab_AllProcesses)
        self.but_projects_new.setEnabled(False)
        self.but_projects_new.setObjectName(_fromUtf8("but_projects_new"))
        self.horizontalLayout_4.addWidget(self.but_projects_new)
        self.but_projects_edit = QtGui.QPushButton(self.tab_AllProcesses)
        self.but_projects_edit.setObjectName(_fromUtf8("but_projects_edit"))
        self.horizontalLayout_4.addWidget(self.but_projects_edit)
        self.but_projects_set_finished = QtGui.QPushButton(self.tab_AllProcesses)
        self.but_projects_set_finished.setObjectName(_fromUtf8("but_projects_set_finished"))
        self.horizontalLayout_4.addWidget(self.but_projects_set_finished)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.textBrowser_project = QtGui.QTextBrowser(self.tab_AllProcesses)
        self.textBrowser_project.setMinimumSize(QtCore.QSize(0, 200))
        self.textBrowser_project.setObjectName(_fromUtf8("textBrowser_project"))
        self.horizontalLayout_6.addWidget(self.textBrowser_project)
        self.verticalLayout_23.addLayout(self.horizontalLayout_6)
        self.Global_tabs.addTab(self.tab_AllProcesses, _fromUtf8(""))
        self.tab_Simulation = QtGui.QWidget()
        self.tab_Simulation.setObjectName(_fromUtf8("tab_Simulation"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tab_Simulation)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit_find_var_mainsim = QtGui.QLineEdit(self.tab_Simulation)
        self.lineEdit_find_var_mainsim.setObjectName(_fromUtf8("lineEdit_find_var_mainsim"))
        self.verticalLayout_2.addWidget(self.lineEdit_find_var_mainsim)
        self.listView_main_sim = QtGui.QListView(self.tab_Simulation)
        self.listView_main_sim.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listView_main_sim.setObjectName(_fromUtf8("listView_main_sim"))
        self.verticalLayout_2.addWidget(self.listView_main_sim)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.SIM_info_tabs = QtGui.QTabWidget(self.tab_Simulation)
        self.SIM_info_tabs.setTabPosition(QtGui.QTabWidget.West)
        self.SIM_info_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.SIM_info_tabs.setObjectName(_fromUtf8("SIM_info_tabs"))
        self.SIM_INF_plot = QtGui.QWidget()
        self.SIM_INF_plot.setObjectName(_fromUtf8("SIM_INF_plot"))
        self.verticalLayout = QtGui.QVBoxLayout(self.SIM_INF_plot)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.button_home = QtGui.QPushButton(self.SIM_INF_plot)
        self.button_home.setObjectName(_fromUtf8("button_home"))
        self.horizontalLayout_14.addWidget(self.button_home)
        self.button_zoom = QtGui.QPushButton(self.SIM_INF_plot)
        self.button_zoom.setObjectName(_fromUtf8("button_zoom"))
        self.horizontalLayout_14.addWidget(self.button_zoom)
        self.button_pan = QtGui.QPushButton(self.SIM_INF_plot)
        self.button_pan.setObjectName(_fromUtf8("button_pan"))
        self.horizontalLayout_14.addWidget(self.button_pan)
        self.button_saveplot = QtGui.QPushButton(self.SIM_INF_plot)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Users/vyakhorev/.designer/backup/icons/save_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Users/vyakhorev/.designer/backup/icons/save_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Users/vyakhorev/.designer/backup/icons/save_icon.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Users/vyakhorev/.designer/backup/icons/save_icon.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_saveplot.setIcon(icon)
        self.button_saveplot.setObjectName(_fromUtf8("button_saveplot"))
        self.horizontalLayout_14.addWidget(self.button_saveplot)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.SIM_INF_mpl_plot = MatplotlibWidget(self.SIM_INF_plot)
        self.SIM_INF_mpl_plot.setObjectName(_fromUtf8("SIM_INF_mpl_plot"))
        self.verticalLayout.addWidget(self.SIM_INF_mpl_plot)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.pushButton_HashSimulPlan = QtGui.QPushButton(self.SIM_INF_plot)
        self.pushButton_HashSimulPlan.setObjectName(_fromUtf8("pushButton_HashSimulPlan"))
        self.horizontalLayout_23.addWidget(self.pushButton_HashSimulPlan)
        self.pushButton_HashSimulProblem = QtGui.QPushButton(self.SIM_INF_plot)
        self.pushButton_HashSimulProblem.setObjectName(_fromUtf8("pushButton_HashSimulProblem"))
        self.horizontalLayout_23.addWidget(self.pushButton_HashSimulProblem)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.SIM_info_tabs.addTab(self.SIM_INF_plot, _fromUtf8(""))
        self.SIM_INF_report = QtGui.QWidget()
        self.SIM_INF_report.setObjectName(_fromUtf8("SIM_INF_report"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.SIM_INF_report)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.textBrowser_Simulation = QtGui.QTextBrowser(self.SIM_INF_report)
        self.textBrowser_Simulation.setObjectName(_fromUtf8("textBrowser_Simulation"))
        self.horizontalLayout_19.addWidget(self.textBrowser_Simulation)
        self.SIM_info_tabs.addTab(self.SIM_INF_report, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.SIM_info_tabs)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.Global_tabs.addTab(self.tab_Simulation, _fromUtf8(""))
        self.tab_SimulLog = QtGui.QWidget()
        self.tab_SimulLog.setObjectName(_fromUtf8("tab_SimulLog"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_SimulLog)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pushButton_log_run_simul_random = QtGui.QPushButton(self.tab_SimulLog)
        self.pushButton_log_run_simul_random.setObjectName(_fromUtf8("pushButton_log_run_simul_random"))
        self.horizontalLayout_15.addWidget(self.pushButton_log_run_simul_random)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem16)
        self.button_log_run_simul = QtGui.QPushButton(self.tab_SimulLog)
        self.button_log_run_simul.setMaximumSize(QtCore.QSize(16777215, 41))
        self.button_log_run_simul.setObjectName(_fromUtf8("button_log_run_simul"))
        self.horizontalLayout_15.addWidget(self.button_log_run_simul)
        self.seed_cmbx = QtGui.QComboBox(self.tab_SimulLog)
        self.seed_cmbx.setMinimumSize(QtCore.QSize(300, 0))
        self.seed_cmbx.setEditable(True)
        self.seed_cmbx.setObjectName(_fromUtf8("seed_cmbx"))
        self.horizontalLayout_15.addWidget(self.seed_cmbx)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.tabWidget_testsim = QtGui.QTabWidget(self.tab_SimulLog)
        self.tabWidget_testsim.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_testsim.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_testsim.setObjectName(_fromUtf8("tabWidget_testsim"))
        self.tab_log = QtGui.QWidget()
        self.tab_log.setObjectName(_fromUtf8("tab_log"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_log)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineEdit_SearchInLog = QtGui.QLineEdit(self.tab_log)
        self.lineEdit_SearchInLog.setObjectName(_fromUtf8("lineEdit_SearchInLog"))
        self.verticalLayout_9.addWidget(self.lineEdit_SearchInLog)
        self.log_table_browser = QtGui.QTableView(self.tab_log)
        self.log_table_browser.setObjectName(_fromUtf8("log_table_browser"))
        self.verticalLayout_9.addWidget(self.log_table_browser)
        self.tabWidget_testsim.addTab(self.tab_log, _fromUtf8(""))
        self.tab_variables = QtGui.QWidget()
        self.tab_variables.setObjectName(_fromUtf8("tab_variables"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_variables)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lineEdit_testsim_findvar = QtGui.QLineEdit(self.tab_variables)
        self.lineEdit_testsim_findvar.setObjectName(_fromUtf8("lineEdit_testsim_findvar"))
        self.verticalLayout_14.addWidget(self.lineEdit_testsim_findvar)
        self.listView_log_var_list = QtGui.QListView(self.tab_variables)
        self.listView_log_var_list.setObjectName(_fromUtf8("listView_log_var_list"))
        self.verticalLayout_14.addWidget(self.listView_log_var_list)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.mplwidget_testsim = MatplotlibWidget(self.tab_variables)
        self.mplwidget_testsim.setObjectName(_fromUtf8("mplwidget_testsim"))
        self.horizontalLayout_12.addWidget(self.mplwidget_testsim)
        self.tabWidget_testsim.addTab(self.tab_variables, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.tabWidget_testsim)
        self.Global_tabs.addTab(self.tab_SimulLog, _fromUtf8(""))
        self.tab_InitialData = QtGui.QWidget()
        self.tab_InitialData.setObjectName(_fromUtf8("tab_InitialData"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tab_InitialData)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.treeWidget_InitialData = QtGui.QTreeWidget(self.tab_InitialData)
        self.treeWidget_InitialData.setMaximumSize(QtCore.QSize(303, 16777215))
        self.treeWidget_InitialData.setObjectName(_fromUtf8("treeWidget_InitialData"))
        self.horizontalLayout_17.addWidget(self.treeWidget_InitialData)
        self.textBrowser_InitialData = QtGui.QTextBrowser(self.tab_InitialData)
        self.textBrowser_InitialData.setObjectName(_fromUtf8("textBrowser_InitialData"))
        self.horizontalLayout_17.addWidget(self.textBrowser_InitialData)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.Global_tabs.addTab(self.tab_InitialData, _fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.Global_tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.AdminMenu = QtGui.QMenu(self.menubar)
        self.AdminMenu.setObjectName(_fromUtf8("AdminMenu"))
        self.FastAddMenu = QtGui.QMenu(self.menubar)
        self.FastAddMenu.setAcceptDrops(True)
        self.FastAddMenu.setObjectName(_fromUtf8("FastAddMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Run_Simulate = QtGui.QAction(MainWindow)
        self.action_Run_Simulate.setObjectName(_fromUtf8("action_Run_Simulate"))
        self.action_Synhronize_xm_with_db = QtGui.QAction(MainWindow)
        self.action_Synhronize_xm_with_db.setObjectName(_fromUtf8("action_Synhronize_xm_with_db"))
        self.action_upload_budget_csv = QtGui.QAction(MainWindow)
        self.action_upload_budget_csv.setObjectName(_fromUtf8("action_upload_budget_csv"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_fast_NewContact = QtGui.QAction(MainWindow)
        self.action_fast_NewContact.setObjectName(_fromUtf8("action_fast_NewContact"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_AddFastNote = QtGui.QAction(MainWindow)
        self.action_AddFastNote.setObjectName(_fromUtf8("action_AddFastNote"))
        self.action_AddNewContact = QtGui.QAction(MainWindow)
        self.action_AddNewContact.setObjectName(_fromUtf8("action_AddNewContact"))
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.action_AddNewCP = QtGui.QAction(MainWindow)
        self.action_AddNewCP.setObjectName(_fromUtf8("action_AddNewCP"))
        self.AdminMenu.addAction(self.action_Run_Simulate)
        self.AdminMenu.addAction(self.action_Synhronize_xm_with_db)
        self.AdminMenu.addAction(self.action_upload_budget_csv)
        self.FastAddMenu.addAction(self.action_AddFastNote)
        self.FastAddMenu.addSeparator()
        self.FastAddMenu.addAction(self.action_AddNewContact)
        self.FastAddMenu.addAction(self.action_AddNewCP)
        self.menubar.addAction(self.FastAddMenu.menuAction())
        self.menubar.addAction(self.AdminMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.Global_tabs.setCurrentIndex(2)
        self.tab_counterparty_settings.setCurrentIndex(0)
        self.tabWidget_KnBaseSource.setCurrentIndex(0)
        self.SIM_info_tabs.setCurrentIndex(0)
        self.tabWidget_testsim.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Business ", None))
        self.pushButton_NewCounterparty.setText(_translate("MainWindow", "Новый", None))
        self.pushButton_EditCounterparty.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_ToCPKnBase.setText(_translate("MainWindow", ">> База знаний >>", None))
        self.pushButton_ToCPContatcts.setText(_translate("MainWindow", ">> Контакты >>", None))
        self.pushButton_ToCPForecast.setText(_translate("MainWindow", ">> Прогноз >>", None))
        self.pushButton_HashCPblank.setText(_translate("MainWindow", "#CPName", None))
        self.pushButton_add_contact_to_company.setText(_translate("MainWindow", "+Контакт", None))
        self.pushButton_PrintCPCard.setText(_translate("MainWindow", "Печать", None))
        self.pushButton_SendCPCard.setText(_translate("MainWindow", "E-mail", None))
        self.tab_counterparty_settings.setTabText(self.tab_counterparty_settings.indexOf(self.tab_CPOverview), _translate("MainWindow", "Карточка", None))
        self.pushButton_ToCPKnBase_Consumption.setText(_translate("MainWindow", ">> База знаний >>", None))
        self.pushButton_HashBudget.setText(_translate("MainWindow", "#Бюджет", None))
        self.but_estimate_ship_stats.setText(_translate("MainWindow", "Оценить по истории", None))
        self.pushButton_AddMaterialFlowToClient.setText(_translate("MainWindow", "Добавить", None))
        self.pushButton_EditMaterialFlowFromClient.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_DeleteMaterialFlowFromClient.setText(_translate("MainWindow", "Удалить", None))
        self.tab_counterparty_settings.setTabText(self.tab_counterparty_settings.indexOf(self.tab_ClientConsumption), _translate("MainWindow", "Бюджет", None))
        self.pushButton_ToCPKnBase_Consumption_2.setText(_translate("MainWindow", ">> База знаний >>", None))
        self.pushButton_HashClientDevelopment.setText(_translate("MainWindow", "#Lead", None))
        self.pushButton_create_matflow.setText(_translate("MainWindow", "Старт продаж", None))
        self.pushButton_AddOppToClient.setText(_translate("MainWindow", "Добавить", None))
        self.pushButton_EditOppClient.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_DeleteOppClient.setText(_translate("MainWindow", "Удалить", None))
        self.tab_counterparty_settings.setTabText(self.tab_counterparty_settings.indexOf(self.tab), _translate("MainWindow", "Leads", None))
        self.pushButton_ToCPKnBase_offers.setText(_translate("MainWindow", ">> База знаний >>", None))
        self.pushButton_HashClientOffer.setText(_translate("MainWindow", "#Офер", None))
        self.pushButton_AddPriceToClient.setText(_translate("MainWindow", "Добавить", None))
        self.pushButton_EditPriceToClient.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_DeletePriceFromClient.setText(_translate("MainWindow", "Удалить", None))
        self.tab_counterparty_settings.setTabText(self.tab_counterparty_settings.indexOf(self.tab_ClientOffers), _translate("MainWindow", "Цены", None))
        self.pushButton_ToCPKnBase_prices.setText(_translate("MainWindow", ">> База знаний >>", None))
        self.pushButton_HashSupplierPrice.setText(_translate("MainWindow", "#Прайс", None))
        self.pushButton_AddPriceToSupplier.setText(_translate("MainWindow", "Добавить", None))
        self.pushButton_EditPriceToSupplier.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_DeletePriceFromSupplier.setText(_translate("MainWindow", "Удалить", None))
        self.tab_counterparty_settings.setTabText(self.tab_counterparty_settings.indexOf(self.tab_SupplierPrices), _translate("MainWindow", "Прайсы", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_Clients), _translate("MainWindow", "Контрагенты", None))
        self.pushButton_add_contact.setText(_translate("MainWindow", "Добавить", None))
        self.pushButton_edit_contact.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_delete_contact.setText(_translate("MainWindow", "Удалить", None))
        self.pushButton_HashClientMeetingContact.setText(_translate("MainWindow", "#Беседа", None))
        self.pushButton_WriteALetterToContact.setText(_translate("MainWindow", ">> E-mail >>", None))
        self.pushButton_PrintContactInfo.setText(_translate("MainWindow", "Печать", None))
        self.pushButton_SendContactInfo.setText(_translate("MainWindow", "E-mail", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_Contacts), _translate("MainWindow", "Контакты", None))
        self.pushButton_KnBaseEmptyNote.setText(_translate("MainWindow", "+ Быстрая заметка", None))
        self.pushButton_RenameHashtag.setText(_translate("MainWindow", "Переименовать", None))
        self.pushButton_SwitchFromHashtagToRecords.setText(_translate("MainWindow", ">> К записям >>", None))
        self.tabWidget_KnBaseSource.setTabText(self.tabWidget_KnBaseSource.indexOf(self.tab_tag_search), _translate("MainWindow", "По тематике", None))
        self.pushButton_KnBaseRunRecordSearch.setText(_translate("MainWindow", "Поискать получше", None))
        self.pushButton_AddNoteKnBase.setText(_translate("MainWindow", "Добавить", None))
        self.pushButton_EditNoteKnBase.setText(_translate("MainWindow", "Изменить", None))
        self.pushButton_DeleteNoteKnBase.setText(_translate("MainWindow", "Удалить", None))
        self.tabWidget_KnBaseSource.setTabText(self.tabWidget_KnBaseSource.indexOf(self.tab_record_search), _translate("MainWindow", "По записям", None))
        self.pushButton_update_themefilt.setText(_translate("MainWindow", "Запросить тэги", None))
        self.pushButton_PrintKnBaseView.setText(_translate("MainWindow", "Печать", None))
        self.pushButton_EmailKnBaseView.setText(_translate("MainWindow", "E-mail", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_KnBase), _translate("MainWindow", "База знаний", None))
        self.but_projects_delete.setText(_translate("MainWindow", "Удалить", None))
        self.but_projects_new.setText(_translate("MainWindow", "Создать", None))
        self.but_projects_edit.setText(_translate("MainWindow", "Редактировать", None))
        self.but_projects_set_finished.setText(_translate("MainWindow", "Выполнено", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_AllProcesses), _translate("MainWindow", "Процессы", None))
        self.button_home.setText(_translate("MainWindow", "Home", None))
        self.button_zoom.setText(_translate("MainWindow", "Zoom", None))
        self.button_pan.setText(_translate("MainWindow", "Pan", None))
        self.button_saveplot.setText(_translate("MainWindow", "Save plot", None))
        self.pushButton_HashSimulPlan.setText(_translate("MainWindow", "#План", None))
        self.pushButton_HashSimulProblem.setText(_translate("MainWindow", "#Проблема", None))
        self.SIM_info_tabs.setTabText(self.SIM_info_tabs.indexOf(self.SIM_INF_plot), _translate("MainWindow", "Plot", None))
        self.SIM_info_tabs.setTabText(self.SIM_info_tabs.indexOf(self.SIM_INF_report), _translate("MainWindow", "Report", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_Simulation), _translate("MainWindow", "Прогноз", None))
        self.pushButton_log_run_simul_random.setText(_translate("MainWindow", "Случайная эпоха", None))
        self.button_log_run_simul.setText(_translate("MainWindow", "Запуск выбранной эпохи:", None))
        self.tabWidget_testsim.setTabText(self.tabWidget_testsim.indexOf(self.tab_log), _translate("MainWindow", "Лог", None))
        self.tabWidget_testsim.setTabText(self.tabWidget_testsim.indexOf(self.tab_variables), _translate("MainWindow", "Переменные", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_SimulLog), _translate("MainWindow", "Тест - симуляция", None))
        self.treeWidget_InitialData.headerItem().setText(0, _translate("MainWindow", "Item", None))
        self.treeWidget_InitialData.headerItem().setText(1, _translate("MainWindow", "Status", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_InitialData), _translate("MainWindow", "Данные", None))
        self.AdminMenu.setTitle(_translate("MainWindow", "Администрирование", None))
        self.FastAddMenu.setTitle(_translate("MainWindow", "Добавить", None))
        self.action_Run_Simulate.setText(_translate("MainWindow", "Запуск симуляции", None))
        self.action_Synhronize_xm_with_db.setText(_translate("MainWindow", "Загрузить из 1С", None))
        self.action_upload_budget_csv.setText(_translate("MainWindow", "Выгрузить в 1С", None))
        self.action_2.setText(_translate("MainWindow", "#ЗапросТовара", None))
        self.action_3.setText(_translate("MainWindow", "#Бюджет", None))
        self.action_4.setText(_translate("MainWindow", "#Офер", None))
        self.action_5.setText(_translate("MainWindow", "#Прайс", None))
        self.action_6.setText(_translate("MainWindow", "#Беседа", None))
        self.action_fast_NewContact.setText(_translate("MainWindow", "Новый контакт", None))
        self.action.setText(_translate("MainWindow", "Заметка", None))
        self.action_AddFastNote.setText(_translate("MainWindow", "+ Быстрая заметка", None))
        self.action_AddNewContact.setText(_translate("MainWindow", "+ Контакт", None))
        self.action_7.setText(_translate("MainWindow", "+ Клиент", None))
        self.action_8.setText(_translate("MainWindow", "+ Поставщик", None))
        self.action_AddNewCP.setText(_translate("MainWindow", "+ Контрагент", None))

from matplotlibwidget import MatplotlibWidget
