# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Code\SimpleBusiness\ui\ModernMainWindow_v2.ui'
#
# Created: Thu Jan 28 00:26:17 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowModern(object):
    def setupUi(self, MainWindowModern):
        MainWindowModern.setObjectName(_fromUtf8("MainWindowModern"))
        MainWindowModern.setWindowModality(QtCore.Qt.NonModal)
        MainWindowModern.resize(663, 799)
        MainWindowModern.setDocumentMode(False)
        MainWindowModern.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindowModern)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.Global_tabs = QtGui.QTabWidget(self.centralwidget)
        self.Global_tabs.setEnabled(True)
        self.Global_tabs.setTabPosition(QtGui.QTabWidget.North)
        self.Global_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.Global_tabs.setDocumentMode(False)
        self.Global_tabs.setObjectName(_fromUtf8("Global_tabs"))
        self.tab_Clients = QtGui.QWidget()
        self.tab_Clients.setObjectName(_fromUtf8("tab_Clients"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_Clients)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit_ClientFilter = QtGui.QLineEdit(self.tab_Clients)
        self.lineEdit_ClientFilter.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_ClientFilter.setObjectName(_fromUtf8("lineEdit_ClientFilter"))
        self.verticalLayout.addWidget(self.lineEdit_ClientFilter)
        self.listView_ClientList = QtGui.QListView(self.tab_Clients)
        self.listView_ClientList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listView_ClientList.setObjectName(_fromUtf8("listView_ClientList"))
        self.verticalLayout.addWidget(self.listView_ClientList)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.Global_tabs.addTab(self.tab_Clients, _fromUtf8(""))
        self.tab_KnBase = QtGui.QWidget()
        self.tab_KnBase.setObjectName(_fromUtf8("tab_KnBase"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_KnBase)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_KnBaseEmptyNote = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_KnBaseEmptyNote.setObjectName(_fromUtf8("pushButton_KnBaseEmptyNote"))
        self.horizontalLayout_3.addWidget(self.pushButton_KnBaseEmptyNote)
        self.lineEdit_KnBase_Search = QtGui.QLineEdit(self.tab_KnBase)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_KnBase_Search.setFont(font)
        self.lineEdit_KnBase_Search.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_KnBase_Search.setObjectName(_fromUtf8("lineEdit_KnBase_Search"))
        self.horizontalLayout_3.addWidget(self.lineEdit_KnBase_Search)
        self.pushButton_SearchKnBase = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_SearchKnBase.setObjectName(_fromUtf8("pushButton_SearchKnBase"))
        self.horizontalLayout_3.addWidget(self.pushButton_SearchKnBase)
        self.pushButton_LastRecords = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_LastRecords.setObjectName(_fromUtf8("pushButton_LastRecords"))
        self.horizontalLayout_3.addWidget(self.pushButton_LastRecords)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listView_Hashtags = QtGui.QListView(self.tab_KnBase)
        self.listView_Hashtags.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listView_Hashtags.setObjectName(_fromUtf8("listView_Hashtags"))
        self.verticalLayout_2.addWidget(self.listView_Hashtags)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_RenameHashtag = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_RenameHashtag.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_RenameHashtag.setObjectName(_fromUtf8("pushButton_RenameHashtag"))
        self.horizontalLayout.addWidget(self.pushButton_RenameHashtag)
        self.pushButton_DeleteHashtag = QtGui.QPushButton(self.tab_KnBase)
        self.pushButton_DeleteHashtag.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_DeleteHashtag.setObjectName(_fromUtf8("pushButton_DeleteHashtag"))
        self.horizontalLayout.addWidget(self.pushButton_DeleteHashtag)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.scrollArea_KnBaseRecords = QtGui.QScrollArea(self.tab_KnBase)
        self.scrollArea_KnBaseRecords.setWidgetResizable(True)
        self.scrollArea_KnBaseRecords.setObjectName(_fromUtf8("scrollArea_KnBaseRecords"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 304, 661))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea_KnBaseRecords.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea_KnBaseRecords)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.Global_tabs.addTab(self.tab_KnBase, _fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.Global_tabs)
        MainWindowModern.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindowModern)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowModern.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindowModern)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindowModern.setMenuBar(self.menuBar)
        self.action_Run_Simulate = QtGui.QAction(MainWindowModern)
        self.action_Run_Simulate.setObjectName(_fromUtf8("action_Run_Simulate"))
        self.action_Synhronize_xm_with_db = QtGui.QAction(MainWindowModern)
        self.action_Synhronize_xm_with_db.setObjectName(_fromUtf8("action_Synhronize_xm_with_db"))
        self.action_upload_budget_csv = QtGui.QAction(MainWindowModern)
        self.action_upload_budget_csv.setObjectName(_fromUtf8("action_upload_budget_csv"))
        self.action_2 = QtGui.QAction(MainWindowModern)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindowModern)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(MainWindowModern)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(MainWindowModern)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(MainWindowModern)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_fast_NewContact = QtGui.QAction(MainWindowModern)
        self.action_fast_NewContact.setObjectName(_fromUtf8("action_fast_NewContact"))
        self.action = QtGui.QAction(MainWindowModern)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_AddFastNote = QtGui.QAction(MainWindowModern)
        self.action_AddFastNote.setObjectName(_fromUtf8("action_AddFastNote"))
        self.action_AddNewContact = QtGui.QAction(MainWindowModern)
        self.action_AddNewContact.setObjectName(_fromUtf8("action_AddNewContact"))
        self.action_7 = QtGui.QAction(MainWindowModern)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_8 = QtGui.QAction(MainWindowModern)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.action_AddNewCP = QtGui.QAction(MainWindowModern)
        self.action_AddNewCP.setObjectName(_fromUtf8("action_AddNewCP"))
        self.action_Refresh = QtGui.QAction(MainWindowModern)
        self.action_Refresh.setObjectName(_fromUtf8("action_Refresh"))
        self.action_ReportPrices = QtGui.QAction(MainWindowModern)
        self.action_ReportPrices.setObjectName(_fromUtf8("action_ReportPrices"))
        self.action_12 = QtGui.QAction(MainWindowModern)
        self.action_12.setObjectName(_fromUtf8("action_12"))
        self.action_ReportInvoicePrices = QtGui.QAction(MainWindowModern)
        self.action_ReportInvoicePrices.setObjectName(_fromUtf8("action_ReportInvoicePrices"))
        self.action_14 = QtGui.QAction(MainWindowModern)
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.action_ReportSalesForecast = QtGui.QAction(MainWindowModern)
        self.action_ReportSalesForecast.setObjectName(_fromUtf8("action_ReportSalesForecast"))
        self.menu.addAction(self.action_ReportPrices)
        self.menu.addAction(self.action_ReportInvoicePrices)
        self.menu.addAction(self.action_ReportSalesForecast)
        self.menu_2.addAction(self.action_Refresh)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindowModern)
        self.Global_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowModern)

    def retranslateUi(self, MainWindowModern):
        MainWindowModern.setWindowTitle(_translate("MainWindowModern", "Simple Business ", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_Clients), _translate("MainWindowModern", "Контрагенты", None))
        self.pushButton_KnBaseEmptyNote.setText(_translate("MainWindowModern", "+ Новая заметка", None))
        self.pushButton_SearchKnBase.setText(_translate("MainWindowModern", "Найти", None))
        self.pushButton_LastRecords.setText(_translate("MainWindowModern", "Свежие", None))
        self.pushButton_RenameHashtag.setText(_translate("MainWindowModern", "Переименовать", None))
        self.pushButton_DeleteHashtag.setText(_translate("MainWindowModern", "Удалить", None))
        self.Global_tabs.setTabText(self.Global_tabs.indexOf(self.tab_KnBase), _translate("MainWindowModern", "База знаний", None))
        self.menu.setTitle(_translate("MainWindowModern", "Отчеты", None))
        self.menu_2.setTitle(_translate("MainWindowModern", "Команды", None))
        self.action_Run_Simulate.setText(_translate("MainWindowModern", "Запуск симуляции", None))
        self.action_Synhronize_xm_with_db.setText(_translate("MainWindowModern", "Загрузить из 1С", None))
        self.action_upload_budget_csv.setText(_translate("MainWindowModern", "Выгрузить в 1С", None))
        self.action_2.setText(_translate("MainWindowModern", "#ЗапросТовара", None))
        self.action_3.setText(_translate("MainWindowModern", "#Бюджет", None))
        self.action_4.setText(_translate("MainWindowModern", "#Офер", None))
        self.action_5.setText(_translate("MainWindowModern", "#Прайс", None))
        self.action_6.setText(_translate("MainWindowModern", "#Беседа", None))
        self.action_fast_NewContact.setText(_translate("MainWindowModern", "Новый контакт", None))
        self.action.setText(_translate("MainWindowModern", "Заметка", None))
        self.action_AddFastNote.setText(_translate("MainWindowModern", "+ Быстрая заметка", None))
        self.action_AddNewContact.setText(_translate("MainWindowModern", "+ Контакт", None))
        self.action_7.setText(_translate("MainWindowModern", "+ Клиент", None))
        self.action_8.setText(_translate("MainWindowModern", "+ Поставщик", None))
        self.action_AddNewCP.setText(_translate("MainWindowModern", "+ Контрагент", None))
        self.action_Refresh.setText(_translate("MainWindowModern", "Обновить", None))
        self.action_Refresh.setShortcut(_translate("MainWindowModern", "Ctrl+R", None))
        self.action_ReportPrices.setText(_translate("MainWindowModern", "Список цен продажи", None))
        self.action_12.setText(_translate("MainWindowModern", "Список цен (подробно)", None))
        self.action_ReportInvoicePrices.setText(_translate("MainWindowModern", "Список прайсов", None))
        self.action_14.setText(_translate("MainWindowModern", "Список прайсов (подробно)", None))
        self.action_ReportSalesForecast.setText(_translate("MainWindowModern", "Прогноз продаж", None))

